# Generated by Django 5.2.17 on 2026-08-28 11:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('vehicle_types', models.CharField(blank=True, max_length=255, verbose_name='Типы транспорта')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Рейтинг')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'перевозчик',
                'verbose_name_plural': 'перевозчики',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Номер заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('planned', 'Назначена'), ('loading', 'На погрузке'), ('in_transit', 'В пути'), ('delivered', 'Доставлена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('cargo_name', models.CharField(max_length=255, verbose_name='Груз')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Вес, кг')),
                ('volume_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Объём, м³')),
                ('vehicle_type', models.CharField(blank=True, max_length=100, verbose_name='Тип транспорта')),
                ('pickup_city', models.CharField(max_length=120, verbose_name='Город погрузки')),
                ('pickup_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес погрузки')),
                ('pickup_date', models.DateField(verbose_name='Дата погрузки')),
                ('delivery_city', models.CharField(max_length=120, verbose_name='Город выгрузки')),
                ('delivery_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес выгрузки')),
                ('delivery_date', models.DateField(verbose_name='Плановая дата выгрузки')),
                ('customer_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ставка клиенту')),
                ('carrier_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ставка перевозчику')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('payment_status', models.CharField(choices=[('awaiting', 'Ожидается'), ('partial', 'Частично'), ('paid', 'Оплачено'), ('overdue', 'Просрочено')], default='awaiting', max_length=20, verbose_name='Оплата')),
                ('customer_reference', models.CharField(blank=True, max_length=100, verbose_name='Номер клиента')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='crm.carrier', verbose_name='Перевозчик')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='crm.customer', verbose_name='Клиент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ('-pickup_date', '-created_at'),
            },
        ),
    ]
