# Generated by Django 5.2.17 on 2026-08-28 12:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес регистрации')),
                ('passport_series', models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан паспорт')),
                ('passport_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('license_number', models.CharField(max_length=30, verbose_name='Номер водительского удостоверения')),
                ('license_categories', models.CharField(help_text='Например: B, C, CE', max_length=50, verbose_name='Категории')),
                ('license_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи удостоверения')),
                ('license_expiry_date', models.DateField(verbose_name='Удостоверение действительно до')),
                ('medical_certificate_expiry', models.DateField(blank=True, null=True, verbose_name='Медсправка действительна до')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='crm.carrier', verbose_name='Перевозчик')),
            ],
            options={
                'verbose_name': 'водитель',
                'verbose_name_plural': 'водители',
                'ordering': ('last_name', 'first_name', 'middle_name'),
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='crm.driver', verbose_name='Водитель'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('truck', 'Грузовой автомобиль'), ('tractor', 'Седельный тягач'), ('van', 'Фургон'), ('trailer', 'Прицеп'), ('semitrailer', 'Полуприцеп'), ('other', 'Другое')], max_length=20, verbose_name='Тип единицы')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Государственный номер')),
                ('trailer_registration_number', models.CharField(blank=True, max_length=20, verbose_name='Номер прицепа / полуприцепа')),
                ('vin', models.CharField(blank=True, max_length=32, verbose_name='VIN')),
                ('make', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950)], verbose_name='Год выпуска')),
                ('body_type', models.CharField(blank=True, max_length=100, verbose_name='Тип кузова')),
                ('capacity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Грузоподъёмность, кг')),
                ('volume_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Объём кузова, м³')),
                ('pallet_capacity', models.PositiveSmallIntegerField(default=0, verbose_name='Вместимость, паллет')),
                ('insurance_expiry_date', models.DateField(blank=True, null=True, verbose_name='Страховка действительна до')),
                ('inspection_expiry_date', models.DateField(blank=True, null=True, verbose_name='Техосмотр действителен до')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='В эксплуатации')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='crm.carrier', verbose_name='Перевозчик')),
            ],
            options={
                'verbose_name': 'транспортное средство',
                'verbose_name_plural': 'подвижной состав',
                'ordering': ('registration_number',),
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='crm.vehicle', verbose_name='Транспорт'),
        ),
    ]
