# Generated by Django 5.2.17 on 2026-08-28 12:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_driver_shipment_driver_vehicle_shipment_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='carrier_payment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Оплата перевозчику до'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_payment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Оплата от клиента до'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('direction', models.CharField(choices=[('income', 'Поступление от клиента'), ('expense', 'Оплата перевозчику')], max_length=10, verbose_name='Операция')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата платежа')),
                ('method', models.CharField(choices=[('bank', 'Банковский перевод'), ('cash', 'Наличные'), ('card', 'Банковская карта'), ('offset', 'Взаимозачёт'), ('other', 'Другое')], default='bank', max_length=20, verbose_name='Способ оплаты')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.shipment', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
                'ordering': ('-payment_date', '-created_at'),
            },
        ),
    ]
