# Generated by Django 5.2.17 on 2026-08-28 12:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_shipment_carrier_payment_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата поручения')),
                ('shipper_name', models.CharField(blank=True, max_length=255, verbose_name='Грузоотправитель')),
                ('shipper_tax_id', models.CharField(blank=True, max_length=20, verbose_name='ИНН грузоотправителя')),
                ('shipper_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес грузоотправителя')),
                ('shipper_contact_name', models.CharField(blank=True, max_length=150, verbose_name='Контактное лицо грузоотправителя')),
                ('shipper_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон грузоотправителя')),
                ('consignee_name', models.CharField(blank=True, max_length=255, verbose_name='Грузополучатель')),
                ('consignee_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес грузополучателя')),
                ('consignee_contact_name', models.CharField(blank=True, max_length=150, verbose_name='Контактное лицо грузополучателя')),
                ('consignee_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон грузополучателя')),
                ('pickup_hours', models.CharField(blank=True, max_length=100, verbose_name='Часы работы на погрузке')),
                ('packaging_type', models.CharField(blank=True, max_length=100, verbose_name='Вид упаковки')),
                ('package_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество мест')),
                ('cargo_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Длина груза, м')),
                ('cargo_width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ширина груза, м')),
                ('cargo_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Высота груза, м')),
                ('special_conditions', models.TextField(blank=True, verbose_name='Особые условия и требования')),
                ('cargo_insurance', models.CharField(blank=True, choices=[('', 'Не указано'), ('yes', 'Да'), ('no', 'Нет')], default='', max_length=3, verbose_name='Страхование груза')),
                ('payer', models.CharField(blank=True, max_length=255, verbose_name='Плательщик')),
                ('payment_place', models.CharField(blank=True, max_length=255, verbose_name='Место оплаты')),
                ('expediter_representative', models.CharField(blank=True, max_length=150, verbose_name='Представитель экспедитора')),
                ('client_representative', models.CharField(blank=True, max_length=150, verbose_name='Представитель клиента')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_order', to='crm.shipment', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'экспедиторское поручение',
                'verbose_name_plural': 'экспедиторские поручения',
            },
        ),
    ]
