# Generated by Django 5.2.17 on 2026-08-28 12:59

import crm.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_forwardingorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('trn', 'Транспортная накладная (ТрН)'), ('invoice', 'Счёт'), ('upd', 'УПД'), ('act', 'Акт'), ('vat_invoice', 'Счёт-фактура'), ('other', 'Другое')], max_length=20, verbose_name='Тип документа')),
                ('party', models.CharField(choices=[('customer', 'Клиент'), ('carrier', 'Перевозчик'), ('internal', 'Внутренний документ'), ('other', 'Другой контрагент')], default='customer', max_length=20, verbose_name='Сторона')),
                ('status', models.CharField(choices=[('expected', 'Ожидается'), ('draft', 'Черновик'), ('issued', 'Выставлен'), ('received', 'Получен'), ('signed', 'Подписан'), ('original', 'Оригинал получен'), ('cancelled', 'Аннулирован')], default='expected', max_length=20, verbose_name='Статус')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Ожидаем до')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('file', models.FileField(blank=True, upload_to=crm.models.shipment_document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'xml', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'zip'])], verbose_name='Файл')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_shipment_documents', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.shipment', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'документ по заявке',
                'verbose_name_plural': 'документы по заявкам',
                'ordering': ('-document_date', '-created_at'),
            },
        ),
    ]
