# Generated by Django 5.2.17 on 2026-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_shipmentdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(blank=True, max_length=150, verbose_name='Краткое наименование')),
                ('tax_id', models.CharField(max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=30, verbose_name='ОГРН / ОГРНИП')),
                ('legal_address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование банка')),
                ('bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('settlement_account', models.CharField(blank=True, max_length=30, verbose_name='Расчётный счёт')),
                ('correspondent_account', models.CharField(blank=True, max_length=30, verbose_name='Корреспондентский счёт')),
                ('director_name', models.CharField(blank=True, max_length=150, verbose_name='Руководитель')),
                ('chief_accountant_name', models.CharField(blank=True, max_length=150, verbose_name='Главный бухгалтер')),
                ('default_vat_rate', models.CharField(choices=[('without_vat', 'Без НДС'), ('0', '0%'), ('5', '5%'), ('7', '7%'), ('10', '10%'), ('20', '20% (переходные операции)'), ('22', '22%')], default='without_vat', max_length=20, verbose_name='Ставка НДС по умолчанию')),
            ],
            options={
                'verbose_name': 'реквизиты компании',
                'verbose_name_plural': 'реквизиты компании',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='kpp',
            field=models.CharField(blank=True, max_length=20, verbose_name='КПП'),
        ),
    ]
