# Generated by Django 5.2.17 on 2026-08-28 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_expeditors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations_as_high', to=settings.AUTH_USER_MODEL, verbose_name='Второй участник')),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations_as_low', to=settings.AUTH_USER_MODEL, verbose_name='Первый участник')),
            ],
            options={
                'verbose_name': 'личный диалог',
                'verbose_name_plural': 'личные диалоги',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('text', models.TextField(max_length=4000, verbose_name='Сообщение')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.directconversation', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'сообщение чата',
                'verbose_name_plural': 'сообщения чата',
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='directconversation',
            constraint=models.UniqueConstraint(fields=('user_low', 'user_high'), name='unique_direct_conversation'),
        ),
        migrations.AddConstraint(
            model_name='directconversation',
            constraint=models.CheckConstraint(condition=models.Q(('user_low', models.F('user_high')), _negated=True), name='direct_conversation_different_users'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='crm_chatmes_convers_d26ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['read_at'], name='crm_chatmes_read_at_2b839a_idx'),
        ),
    ]
