# Generated by Django 5.2.17 on 2026-08-28 18:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_directconversation_chatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование банка'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='bik',
            field=models.CharField(blank=True, max_length=20, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=30, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='director_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='kpp',
            field=models.CharField(blank=True, max_length=20, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='ogrn',
            field=models.CharField(blank=True, max_length=30, verbose_name='ОГРН / ОГРНИП'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='settlement_account',
            field=models.CharField(blank=True, max_length=30, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование банка'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bik',
            field=models.CharField(blank=True, max_length=20, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='customer',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=30, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AddField(
            model_name='customer',
            name='director_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ogrn',
            field=models.CharField(blank=True, max_length=30, verbose_name='ОГРН / ОГРНИП'),
        ),
        migrations.AddField(
            model_name='customer',
            name='settlement_account',
            field=models.CharField(blank=True, max_length=30, verbose_name='Расчётный счёт'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('client_forwarding', 'ТЭО с клиентом'), ('carrier_transport', 'Перевозка с перевозчиком'), ('subcontractor_forwarding', 'ТЭО с привлечённым экспедитором')], max_length=40, verbose_name='Тип договора')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер')),
                ('contract_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата договора')),
                ('city', models.CharField(default='Санкт-Петербург', max_length=120, verbose_name='Город подписания')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готов к подписанию'), ('signed', 'Подписан'), ('terminated', 'Расторгнут'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('expeditor_representative', models.CharField(blank=True, max_length=150, verbose_name='Представитель нашей компании')),
                ('expeditor_authority_basis', models.CharField(default='Устава', max_length=150, verbose_name='Основание полномочий')),
                ('counterparty_representative', models.CharField(blank=True, max_length=150, verbose_name='Представитель контрагента')),
                ('counterparty_authority_basis', models.CharField(default='Устава', max_length=150, verbose_name='Основание полномочий контрагента')),
                ('notes', models.TextField(blank=True, verbose_name='Внутренний комментарий')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.carrier', verbose_name='Перевозчик / привлечённый экспедитор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.customer', verbose_name='Клиент')),
                ('expeditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.companyprofile', verbose_name='Наша компания')),
            ],
            options={
                'verbose_name': 'договор',
                'verbose_name_plural': 'договоры',
                'ordering': ('-contract_date', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('expeditor', 'number'), name='unique_contract_number_per_expeditor')],
            },
        ),
    ]
