# Generated by Django 5.2.17 on 2026-08-28 18:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_carrier_address_carrier_bank_name_carrier_bik_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(blank=True, max_length=150, verbose_name='Краткое наименование')),
                ('tax_id', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=30, verbose_name='ОГРН / ОГРНИП')),
                ('legal_address', models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Контактное лицо')),
                ('director_name', models.CharField(blank=True, max_length=150, verbose_name='Руководитель')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование банка')),
                ('bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('settlement_account', models.CharField(blank=True, max_length=30, verbose_name='Расчётный счёт')),
                ('correspondent_account', models.CharField(blank=True, max_length=30, verbose_name='Корреспондентский счёт')),
                ('is_own_company', models.BooleanField(default=False, verbose_name='Наша компания')),
                ('verification_status', models.CharField(choices=[('not_checked', 'Не проверена'), ('verified', 'Проверена'), ('warning', 'Требует проверки')], default='not_checked', max_length=20, verbose_name='Проверка реквизитов')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_own_company', 'is_active'], name='crm_organiz_is_own__b2fae8_idx')],
            },
        ),
        migrations.AddField(
            model_name='carrier',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_carriers', to='crm.organization', verbose_name='Единая карточка'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_expeditors', to='crm.organization', verbose_name='Единая карточка'),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_customers', to='crm.organization', verbose_name='Единая карточка'),
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='Номер рейса')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('client_instruction_received', 'Поручение клиента получено'), ('executor_search', 'Поиск исполнителя'), ('executor_selected', 'Исполнитель найден'), ('executor_documents_verified', 'Документы исполнителя проверены'), ('vehicle_confirmed', 'Машина подтверждена'), ('loading', 'На погрузке'), ('in_transit', 'В пути'), ('unloading', 'На выгрузке'), ('delivered', 'Доставлено'), ('documents_received', 'Документы получены'), ('customer_invoiced', 'Выставлено клиенту'), ('closed', 'Закрыто'), ('on_hold', 'Приостановлено'), ('cancelled', 'Отменено')], default='new', max_length=40, verbose_name='Статус')),
                ('cargo_name', models.CharField(max_length=255, verbose_name='Груз')),
                ('cargo_description', models.TextField(blank=True, verbose_name='Описание груза')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Вес, кг')),
                ('volume_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Объём, м³')),
                ('package_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество мест')),
                ('temperature_regime', models.CharField(blank=True, max_length=100, verbose_name='Температурный режим')),
                ('vehicle_requirements', models.CharField(blank=True, max_length=255, verbose_name='Требования к транспорту')),
                ('special_requirements', models.TextField(blank=True, verbose_name='Особые требования')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата начала')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата окончания')),
                ('legacy_chain_sync', models.BooleanField(default=True, verbose_name='Синхронизировать цепочку со старой заявкой')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('legacy_shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportation', to='crm.shipment', verbose_name='Исходная заявка')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportations', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_transportations', to='crm.organization', verbose_name='Наша компания')),
            ],
            options={
                'verbose_name': 'перевозка / рейс',
                'verbose_name_plural': 'перевозки / рейсы',
                'ordering': ('-planned_start_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TransportationParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('own_company', 'Наша компания / экспедитор'), ('executor', 'Наш исполнитель'), ('forwarder', 'Привлечённый экспедитор'), ('factual_carrier', 'Фактический перевозчик'), ('shipper', 'Грузоотправитель'), ('consignee', 'Грузополучатель'), ('payer', 'Плательщик')], max_length=30, verbose_name='Роль в рейсе')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('source', models.CharField(default='manual', max_length=20, verbose_name='Источник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportation_participations', to='crm.organization', verbose_name='Организация')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='crm.transportation', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'участник рейса',
                'verbose_name_plural': 'участники рейса',
                'ordering': ('sequence', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TransportationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('contractor_role', models.CharField(choices=[('forwarder', 'Экспедитор'), ('carrier', 'Перевозчик')], max_length=20, verbose_name='Роль исполнителя')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('instruction_number', models.CharField(blank=True, max_length=100, verbose_name='Номер поручения / заявки')),
                ('instruction_status', models.CharField(blank=True, max_length=100, verbose_name='Статус поручения / заявки')),
                ('source', models.CharField(default='manual', max_length=20, verbose_name='Источник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Документы проверены')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportation_links', to='crm.contract', verbose_name='Договор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='crm.transportationlink', verbose_name='Предыдущее звено')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_links', to='crm.transportation', verbose_name='Рейс')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_transportation_links', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('contractor_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_links', to='crm.transportationparty', verbose_name='Кому поручили')),
                ('principal_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_links', to='crm.transportationparty', verbose_name='Кто поручил')),
            ],
            options={
                'verbose_name': 'звено цепочки исполнения',
                'verbose_name_plural': 'звенья цепочки исполнения',
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='TransportationStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('kind', models.CharField(choices=[('pickup', 'Погрузка'), ('delivery', 'Выгрузка'), ('intermediate', 'Промежуточная точка')], max_length=20, verbose_name='Тип точки')),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('planned_from', models.DateTimeField(blank=True, null=True, verbose_name='План с')),
                ('planned_to', models.DateTimeField(blank=True, null=True, verbose_name='План до')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое прибытие')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое убытие')),
                ('instructions', models.TextField(blank=True, verbose_name='Инструкции')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportation_stops', to='crm.organization', verbose_name='Организация')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='crm.transportation', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'точка маршрута',
                'verbose_name_plural': 'точки маршрута',
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('trailer_registration_number', models.CharField(blank=True, max_length=20, verbose_name='Номер прицепа / полуприцепа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Текущее назначение')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('actual_carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factual_transportations', to='crm.organization', verbose_name='Фактический перевозчик')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_vehicle_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportation_assignments', to='crm.driver', verbose_name='Водитель')),
                ('execution_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_assignments', to='crm.transportationlink', verbose_name='Конечное звено')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trailer_transportation_assignments', to='crm.vehicle', verbose_name='Прицеп / полуприцеп')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='crm.transportation', verbose_name='Рейс')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportation_assignments', to='crm.vehicle', verbose_name='Тягач / автомобиль')),
            ],
            options={
                'verbose_name': 'назначение транспорта',
                'verbose_name_plural': 'назначения транспорта',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('forwarder', 'Экспедитор'), ('carrier', 'Перевозчик'), ('shipper', 'Грузоотправитель'), ('consignee', 'Грузополучатель'), ('payer', 'Плательщик')], max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='crm.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'роль организации',
                'verbose_name_plural': 'роли организаций',
                'ordering': ('organization', 'role'),
                'constraints': [models.UniqueConstraint(fields=('organization', 'role'), name='unique_organization_role')],
            },
        ),
        migrations.AddIndex(
            model_name='transportation',
            index=models.Index(fields=['owner_company', 'status'], name='crm_transpo_owner_c_07f73a_idx'),
        ),
        migrations.AddIndex(
            model_name='transportation',
            index=models.Index(fields=['planned_start_date', 'planned_end_date'], name='crm_transpo_planned_239275_idx'),
        ),
        migrations.AddIndex(
            model_name='transportation',
            index=models.Index(fields=['manager', 'status'], name='crm_transpo_manager_86e3fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportationparty',
            constraint=models.UniqueConstraint(fields=('transportation', 'organization', 'role'), name='unique_transportation_organization_role'),
        ),
        migrations.AddConstraint(
            model_name='transportationlink',
            constraint=models.UniqueConstraint(fields=('transportation', 'sequence'), name='unique_transportation_link_sequence'),
        ),
        migrations.AddConstraint(
            model_name='transportationstop',
            constraint=models.UniqueConstraint(fields=('transportation', 'sequence'), name='unique_transportation_stop_sequence'),
        ),
        migrations.AddConstraint(
            model_name='vehicleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('transportation',), name='unique_active_vehicle_assignment'),
        ),
    ]
