# Generated by Django 5.2.17 on 2026-08-28 19:44

import django.db.models.deletion
from django.db import migrations, models


def backfill_organization_registers(apps, schema_editor):
    Organization = apps.get_model("crm", "Organization")
    BankAccount = apps.get_model("crm", "OrganizationBankAccount")
    Contact = apps.get_model("crm", "OrganizationContact")
    for organization in Organization.objects.all().iterator():
        if organization.settlement_account and organization.bank_name:
            BankAccount.objects.get_or_create(
                organization=organization,
                account_number=organization.settlement_account,
                defaults={
                    "bank_name": organization.bank_name,
                    "bik": organization.bik,
                    "correspondent_account": organization.correspondent_account,
                    "currency": "RUB",
                    "is_primary": True,
                    "is_active": True,
                },
            )
        if organization.contact_name:
            Contact.objects.get_or_create(
                organization=organization,
                full_name=organization.contact_name,
                defaults={
                    "phone": organization.phone,
                    "email": organization.email,
                    "is_primary": True,
                    "is_active": True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_correct_migrated_planned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('legal_entity', 'Юридическое лицо'), ('entrepreneur', 'Индивидуальный предприниматель'), ('individual', 'Физическое лицо')], default='legal_entity', max_length=20, verbose_name='Вид контрагента'),
        ),
        migrations.AddField(
            model_name='organization',
            name='okato',
            field=models.CharField(blank=True, max_length=20, verbose_name='ОКАТО'),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_country',
            field=models.CharField(default='РОССИЯ', max_length=100, verbose_name='Страна регистрации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование для документов'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Наименование в программе'),
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ф. И. О.')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное контактное лицо')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуально')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_people', to='crm.organization', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'контактное лицо контрагента',
                'verbose_name_plural': 'контактные лица контрагента',
                'ordering': ('-is_primary', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='crm.organizationgroup', verbose_name='Родительская группа')),
            ],
            options={
                'verbose_name': 'группа контрагентов',
                'verbose_name_plural': 'группы контрагентов',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='crm.organizationgroup', verbose_name='В группе'),
        ),
        migrations.CreateModel(
            name='OrganizationBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('account_number', models.CharField(max_length=30, verbose_name='Расчётный счёт')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Наименование банка')),
                ('bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('correspondent_account', models.CharField(blank=True, max_length=30, verbose_name='Корреспондентский счёт')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='crm.organization', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'банковский счёт контрагента',
                'verbose_name_plural': 'банковские счета контрагента',
                'ordering': ('-is_primary', 'bank_name', 'account_number'),
                'constraints': [models.UniqueConstraint(fields=('organization', 'account_number'), name='unique_organization_bank_account')],
            },
        ),
        migrations.RunPython(
            backfill_organization_registers,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='organizationgroup',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_organization_group_name'),
        ),
    ]
