# Generated by Django 5.2.17 on 2026-08-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_organization_kind_organization_okato_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizationbankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('organization',), name='unique_primary_bank_account_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='organizationcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('organization',), name='unique_primary_contact_per_organization'),
        ),
    ]
