# Generated by Django 5.2.17 on 2026-08-30 21:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_erp_core(apps, schema_editor):
    VATRate = apps.get_model("crm", "VATRate")
    PackageType = apps.get_model("crm", "PackageType")
    CargoHandlingMethod = apps.get_model("crm", "CargoHandlingMethod")
    Transportation = apps.get_model("crm", "Transportation")
    TransportationParty = apps.get_model("crm", "TransportationParty")
    TransportationLink = apps.get_model("crm", "TransportationLink")
    TripCharge = apps.get_model("crm", "TripCharge")
    SettlementMovement = apps.get_model("crm", "SettlementMovement")
    Instruction = apps.get_model("crm", "TransportationInstruction")
    Payment = apps.get_model("crm", "Payment")

    rates = {}
    for code, name, value, without_vat in (
        ("without_vat", "Без НДС", "0", True),
        ("0", "НДС 0%", "0", False),
        ("5", "НДС 5%", "5", False),
        ("7", "НДС 7%", "7", False),
        ("10", "НДС 10%", "10", False),
        ("20", "НДС 20%", "20", False),
        ("22", "НДС 22%", "22", False),
    ):
        rates[code], _ = VATRate.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "rate": Decimal(value),
                "is_without_vat": without_vat,
                "is_active": True,
            },
        )
    for name in ("Без упаковки", "Короб", "Паллет", "Мешок", "Ящик"):
        PackageType.objects.get_or_create(name=name)
    for name in ("Задняя", "Боковая", "Верхняя", "Гидроборт", "Ручная"):
        CargoHandlingMethod.objects.get_or_create(name=name)

    def amounts(gross, vat_rate):
        gross = Decimal(gross or 0)
        if vat_rate.is_without_vat or not vat_rate.rate:
            vat = Decimal("0.00")
        else:
            vat = (
                gross * vat_rate.rate / (Decimal("100") + vat_rate.rate)
            ).quantize(Decimal("0.01"))
        return gross - vat, vat

    for transportation in Transportation.objects.select_related(
        "legacy_shipment", "legacy_shipment__expeditor"
    ).all().iterator():
        shipment = transportation.legacy_shipment
        if not shipment:
            continue
        customer_rate_code = shipment.expeditor.default_vat_rate or "without_vat"
        customer_rate = rates.get(customer_rate_code, rates["without_vat"])
        executor_rate = rates["without_vat"]
        document_date = transportation.created_at.date()
        customer_due = shipment.customer_payment_due_date
        executor_due = shipment.carrier_payment_due_date
        customer_term = (
            max((customer_due - shipment.delivery_date).days, 0)
            if customer_due else 0
        )
        executor_term = (
            max((executor_due - shipment.delivery_date).days, 0)
            if executor_due else 0
        )
        Transportation.objects.filter(pk=transportation.pk).update(
            document_date=document_date,
            number_year=document_date.year,
            client_reference=shipment.customer_reference,
            customer_amount=shipment.customer_price,
            customer_vat_rate=customer_rate,
            executor_amount=shipment.carrier_price,
            executor_vat_rate=executor_rate,
            currency=shipment.currency,
            customer_payment_term_days=customer_term,
            executor_payment_term_days=executor_term,
            customer_payment_due_date=customer_due,
            executor_payment_due_date=executor_due,
        )
        client_party = TransportationParty.objects.filter(
            transportation=transportation, role="client", is_active=True
        ).first()
        link = TransportationLink.objects.filter(
            transportation=transportation, is_active=True
        ).select_related("contractor_party").order_by("sequence").first()
        if not client_party or not link or not shipment.customer_price:
            continue
        executor_party = TransportationParty.objects.filter(
            pk=link.contractor_party_id
        ).first()
        if not executor_party:
            continue
        customer_net, customer_vat = amounts(shipment.customer_price, customer_rate)
        executor_net, executor_vat = amounts(shipment.carrier_price, executor_rate)
        TripCharge.objects.create(
            transportation=transportation,
            direction="revenue",
            owner_company_id=transportation.owner_company_id,
            counterparty_id=client_party.organization_id,
            amount=shipment.customer_price,
            amount_without_vat=customer_net,
            vat_amount=customer_vat,
            vat_rate=customer_rate,
            currency=shipment.currency,
            movement_date=document_date,
        )
        TripCharge.objects.create(
            transportation=transportation,
            direction="cost",
            owner_company_id=transportation.owner_company_id,
            counterparty_id=executor_party.organization_id,
            contract_id=link.contract_id,
            amount=shipment.carrier_price,
            amount_without_vat=executor_net,
            vat_amount=executor_vat,
            vat_rate=executor_rate,
            currency=shipment.currency,
            movement_date=document_date,
        )
        SettlementMovement.objects.create(
            transportation=transportation,
            side="receivable",
            kind="accrual",
            owner_company_id=transportation.owner_company_id,
            counterparty_id=client_party.organization_id,
            amount=shipment.customer_price,
            currency=shipment.currency,
            movement_date=document_date,
            due_date=customer_due,
        )
        SettlementMovement.objects.create(
            transportation=transportation,
            side="payable",
            kind="accrual",
            owner_company_id=transportation.owner_company_id,
            counterparty_id=executor_party.organization_id,
            contract_id=link.contract_id,
            amount=shipment.carrier_price,
            currency=shipment.currency,
            movement_date=document_date,
            due_date=executor_due,
        )
        for payment in Payment.objects.filter(shipment=shipment):
            is_income = payment.direction == "income"
            SettlementMovement.objects.create(
                transportation=transportation,
                payment=payment,
                side="receivable" if is_income else "payable",
                kind="payment",
                owner_company_id=transportation.owner_company_id,
                counterparty_id=(
                    client_party.organization_id
                    if is_income else executor_party.organization_id
                ),
                contract_id=None if is_income else link.contract_id,
                amount=-payment.amount,
                currency=shipment.currency,
                movement_date=payment.payment_date,
            )
        if shipment.customer_reference:
            Instruction.objects.get_or_create(
                transportation=transportation,
                kind="client_order",
                defaults={
                    "number": shipment.customer_reference,
                    "document_date": document_date,
                    "counterparty_id": client_party.organization_id,
                    "status": "ready",
                },
            )
        instruction_kind = (
            "carrier_application"
            if link.contractor_role == "carrier" else "forwarder_instruction"
        )
        Instruction.objects.get_or_create(
            transportation=transportation,
            kind=instruction_kind,
            defaults={
                "number": link.instruction_number or f"{transportation.number}-1",
                "document_date": document_date,
                "counterparty_id": executor_party.organization_id,
                "contract_id": link.contract_id,
                "status": "draft",
            },
        )
        Transportation.objects.filter(pk=transportation.pk).update(
            posting_status="posted",
            posted_at=transportation.updated_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_organizationbankaccount_unique_primary_bank_account_per_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoHandlingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
            ],
            options={
                'verbose_name': 'способ погрузки / выгрузки',
                'verbose_name_plural': 'способы погрузки / выгрузки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
            ],
            options={
                'verbose_name': 'вид упаковки',
                'verbose_name_plural': 'виды упаковки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ставка, %')),
                ('is_without_vat', models.BooleanField(default=False, verbose_name='Без НДС')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с')),
            ],
            options={
                'verbose_name': 'ставка НДС',
                'verbose_name_plural': 'ставки НДС',
                'ordering': ('is_without_vat', 'rate'),
            },
        ),
        migrations.AddField(
            model_name='transportation',
            name='client_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер поручения клиента'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='customer_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Клиент платит, всего'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='customer_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_transportations', to='crm.contract', verbose_name='Договор с клиентом'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='customer_payment_due_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Оплата от клиента до'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='customer_payment_term_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Отсрочка клиента, дней'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='document_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата документа'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='executor_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Исполнителю, всего'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='executor_payment_due_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Оплата исполнителю до'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='executor_payment_term_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Отсрочка исполнителю, дней'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='number_year',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Год нумерации'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='pallet_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество паллет'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='payment_due_basis',
            field=models.CharField(choices=[('delivery_date', 'Дата доставки'), ('document_date', 'Дата документа'), ('originals_received', 'Получение оригиналов')], default='delivery_date', max_length=30, verbose_name='Основание срока оплаты'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проведён'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_transportations', to=settings.AUTH_USER_MODEL, verbose_name='Провёл'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='posting_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён'), ('voided', 'Аннулирован')], default='draft', max_length=20, verbose_name='Состояние документа'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='number',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Номер рейса'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='loading_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loading_transportations', to='crm.cargohandlingmethod', verbose_name='Способ погрузки'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='unloading_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unloading_transportations', to='crm.cargohandlingmethod', verbose_name='Способ выгрузки'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportations', to='crm.packagetype', verbose_name='Вид упаковки'),
        ),
        migrations.CreateModel(
            name='SettlementMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('side', models.CharField(choices=[('receivable', 'Дебиторская задолженность'), ('payable', 'Кредиторская задолженность')], max_length=15, verbose_name='Сторона расчётов')),
                ('kind', models.CharField(choices=[('accrual', 'Начисление'), ('payment', 'Оплата')], max_length=10, verbose_name='Вид движения')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Начисление положительное, оплата отрицательная.', max_digits=14, verbose_name='Движение задолженности')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('movement_date', models.DateField(verbose_name='Период')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_movements', to='crm.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_settlement_movements', to='crm.organization', verbose_name='Контрагент')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_movements', to='crm.organization', verbose_name='Наша компания')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlement_movement', to='crm.payment', verbose_name='Платёж-регистратор')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_movements', to='crm.transportation', verbose_name='Заявка / рейс')),
            ],
            options={
                'verbose_name': 'движение взаиморасчётов',
                'verbose_name_plural': 'движения взаиморасчётов',
                'ordering': ('movement_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TransportationInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('client_order', 'Поручение клиента'), ('carrier_application', 'Заявка перевозчику'), ('forwarder_instruction', 'Поручение привлечённому экспедитору')], max_length=30, verbose_name='Вид документа')),
                ('number', models.CharField(max_length=100, verbose_name='Номер')),
                ('document_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Подготовлен'), ('signed', 'Подписан'), ('cancelled', 'Аннулирован')], default='draft', max_length=20, verbose_name='Статус')),
                ('generated_on_posting', models.BooleanField(default=True, verbose_name='Создан при проведении')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportation_instructions', to='crm.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportation_instructions', to='crm.organization', verbose_name='Контрагент')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='crm.transportation', verbose_name='Заявка / рейс')),
            ],
            options={
                'verbose_name': 'поручение / заявка по рейсу',
                'verbose_name_plural': 'поручения / заявки по рейсам',
                'ordering': ('kind', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TransportationNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Последний номер')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation_number_sequences', to='crm.organization', verbose_name='Наша компания')),
            ],
            options={
                'verbose_name': 'нумератор заявок / рейсов',
                'verbose_name_plural': 'нумераторы заявок / рейсов',
            },
        ),
        migrations.CreateModel(
            name='TransportationStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('old_status', models.CharField(blank=True, max_length=40, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(max_length=40, verbose_name='Новый статус')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('source', models.CharField(default='manual', max_length=30, verbose_name='Источник')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportation_status_events', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='crm.transportation', verbose_name='Заявка / рейс')),
            ],
            options={
                'verbose_name': 'событие статуса рейса',
                'verbose_name_plural': 'история статусов рейса',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TripCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('direction', models.CharField(choices=[('revenue', 'Доход'), ('cost', 'Расход')], max_length=10, verbose_name='Вид движения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма всего')),
                ('amount_without_vat', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма без НДС')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма НДС')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('movement_date', models.DateField(verbose_name='Период')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_charges', to='crm.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_trip_charges', to='crm.organization', verbose_name='Контрагент')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_charges', to='crm.organization', verbose_name='Наша компания')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='crm.transportation', verbose_name='Документ-регистратор')),
                ('vat_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_charges', to='crm.vatrate', verbose_name='Ставка НДС')),
            ],
            options={
                'verbose_name': 'движение доходов / расходов',
                'verbose_name_plural': 'движения доходов / расходов',
                'ordering': ('movement_date', 'direction'),
            },
        ),
        migrations.AddField(
            model_name='transportation',
            name='customer_vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_transportations', to='crm.vatrate', verbose_name='НДС клиента'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='executor_vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executor_transportations', to='crm.vatrate', verbose_name='НДС исполнителя'),
        ),
        migrations.RunPython(
            backfill_erp_core,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='transportation',
            index=models.Index(fields=['owner_company', 'posting_status', 'document_date'], name='crm_transpo_owner_c_200508_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportation',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('owner_company', 'number_year', 'number'), name='unique_transportation_number_per_company_year'),
        ),
        migrations.AddConstraint(
            model_name='settlementmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'accrual')), fields=('transportation', 'side', 'kind'), name='unique_trip_settlement_accrual'),
        ),
        migrations.AddConstraint(
            model_name='transportationinstruction',
            constraint=models.UniqueConstraint(fields=('transportation', 'kind'), name='unique_instruction_kind_per_transportation'),
        ),
        migrations.AddConstraint(
            model_name='transportationnumbersequence',
            constraint=models.UniqueConstraint(fields=('owner_company', 'year'), name='unique_transportation_sequence_per_company_year'),
        ),
        migrations.AddConstraint(
            model_name='tripcharge',
            constraint=models.UniqueConstraint(fields=('transportation', 'direction'), name='unique_trip_charge_direction'),
        ),
    ]
