# Generated by Django 5.2.17 on 2026-08-31 07:19

from django.db import migrations, models


def remove_payer_counterparty_role(apps, schema_editor):
    OrganizationRole = apps.get_model("crm", "OrganizationRole")
    OrganizationRole.objects.filter(role="payer").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_cargohandlingmethod_packagetype_vatrate_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_payer_counterparty_role,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('forwarder', 'Экспедитор'), ('carrier', 'Перевозчик'), ('shipper', 'Грузоотправитель'), ('consignee', 'Грузополучатель')], max_length=20, verbose_name='Роль'),
        ),
    ]
