# Generated by Django 5.2.17 on 2026-08-31

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0016_alter_organizationrole_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="profit_tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("25.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Расчётная ставка налога на прибыль, %",
            ),
        ),
    ]
