# Generated by Django 5.2.17 on 2026-08-31 17:16

import crm.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_unique_organization_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, upload_to=crm.models.chat_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'txt', 'rtf', 'odt', 'ods', 'ppt', 'pptx', 'xml', 'json', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'zip', 'rar', '7z', 'eml', 'msg')), crm.models.validate_chat_attachment_size], verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Размер файла'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, max_length=4000, verbose_name='Сообщение'),
        ),
    ]
