# Generated by Django 5.2.17 on 2026-08-31 22:38

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


def backfill_driver_registers(apps, schema_editor):
    Driver = apps.get_model("crm", "Driver")
    DriverEmployment = apps.get_model("crm", "DriverEmployment")
    DriverPassport = apps.get_model("crm", "DriverPassport")
    used_passports = set()
    for driver in Driver.objects.all().iterator():
        DriverEmployment.objects.create(
            driver_id=driver.pk,
            carrier_id=driver.carrier_id,
            is_primary=True,
            is_active=True,
        )
        series = re.sub(r"\D", "", driver.passport_series or "")
        number = re.sub(r"\D", "", driver.passport_number or "")
        identity = (series, number)
        if len(series) != 4 or len(number) != 6 or identity in used_passports:
            continue
        DriverPassport.objects.create(
            driver_id=driver.pk,
            series=series,
            number=number,
            issued_by=driver.passport_issued_by,
            issue_date=driver.passport_issue_date,
            is_current=True,
        )
        used_passports.add(identity)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_chatmessage_attachment_chatmessage_attachment_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное место работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_employments', to='crm.carrier', verbose_name='Компания')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='crm.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'место работы водителя',
                'verbose_name_plural': 'места работы водителей',
                'ordering': ('-is_primary', 'carrier__name'),
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='carriers',
            field=models.ManyToManyField(related_name='associated_drivers', through='crm.DriverEmployment', to='crm.carrier', verbose_name='Компании-работодатели'),
        ),
        migrations.CreateModel(
            name='DriverPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('series', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Серия должна содержать 4 цифры.')], verbose_name='Серия')),
                ('number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Номер должен содержать 6 цифр.')], verbose_name='Номер')),
                ('issued_by', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('is_current', models.BooleanField(default=True, verbose_name='Действующий паспорт')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='crm.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'паспорт водителя',
                'verbose_name_plural': 'паспорта водителей',
                'ordering': ('-is_current', '-issue_date', '-created_at'),
            },
        ),
        migrations.RunPython(
            backfill_driver_registers,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='driveremployment',
            constraint=models.UniqueConstraint(fields=('driver', 'carrier'), name='unique_driver_employment'),
        ),
        migrations.AddConstraint(
            model_name='driveremployment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('driver',), name='unique_primary_driver_employment'),
        ),
        migrations.AddConstraint(
            model_name='driverpassport',
            constraint=models.UniqueConstraint(fields=('series', 'number'), name='unique_driver_passport_identity', violation_error_message='Водитель с такой серией и номером паспорта уже существует.'),
        ),
        migrations.AddConstraint(
            model_name='driverpassport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('driver',), name='unique_current_driver_passport'),
        ),
    ]
