# Generated by Django 5.2.17 on 2026-09-01 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_driveremployment_driver_carriers_driverpassport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'ИНН физлица должен содержать 12 цифр.')], verbose_name='ИНН'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id', ''), _negated=True), fields=('tax_id',), name='unique_driver_tax_id_when_present', violation_error_message='Водитель с таким ИНН уже существует.'),
        ),
    ]
