# Generated by Django 5.2.17 on 2026-09-01 07:47

import django.db.models.deletion
from django.db import migrations, models
import re


def copy_current_driver_licenses(apps, schema_editor):
    Driver = apps.get_model("crm", "Driver")
    DriverLicense = apps.get_model("crm", "DriverLicense")
    used_keys = set()
    for driver in Driver.objects.exclude(license_number="").iterator():
        identity_key = re.sub(
            r"[^0-9A-ZА-Я]", "", (driver.license_number or "").upper()
        )
        if not identity_key or identity_key in used_keys:
            continue
        DriverLicense.objects.create(
            driver_id=driver.pk,
            number=driver.license_number,
            identity_key=identity_key,
            categories=driver.license_categories,
            issue_date=driver.license_issue_date,
            expiry_date=driver.license_expiry_date,
            is_current=True,
        )
        used_keys.add(identity_key)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_driver_tax_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.CharField(max_length=30, verbose_name='Номер удостоверения')),
                ('identity_key', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Нормализованный номер')),
                ('categories', models.CharField(help_text='Например: B, C, CE', max_length=50, verbose_name='Категории')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(verbose_name='Действительно до')),
                ('is_current', models.BooleanField(default=True, verbose_name='Действующее удостоверение')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='crm.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'водительское удостоверение',
                'verbose_name_plural': 'водительские удостоверения',
                'ordering': ('-is_current', '-expiry_date', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('driver',), name='unique_current_driver_license')],
            },
        ),
        migrations.RunPython(
            copy_current_driver_licenses,
            migrations.RunPython.noop,
        ),
    ]
