# Generated by Django 5.2.17 on 2026-09-01 15:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_driver_license_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Номер заказа')),
                ('number_year', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Год нумерации')),
                ('document_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен в рейс'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ставка клиента')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('payment_form', models.CharField(choices=[('bank_with_vat', 'Безналичная, с НДС'), ('bank_without_vat', 'Безналичная, без НДС'), ('cash', 'Наличная')], default='bank_with_vat', max_length=30, verbose_name='Форма оплаты')),
                ('payment_term_days', models.PositiveSmallIntegerField(default=0, verbose_name='Отсрочка, дней')),
                ('cargo_name', models.CharField(max_length=255, verbose_name='Наименование груза')),
                ('cargo_description', models.TextField(blank=True, verbose_name='Характеристики груза')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Вес, кг')),
                ('volume_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Объём, м³')),
                ('package_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество мест')),
                ('pallet_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество паллет')),
                ('temperature_regime', models.CharField(blank=True, max_length=100, verbose_name='Температурный режим')),
                ('vehicle_requirements', models.CharField(blank=True, max_length=255, verbose_name='Требования к транспорту')),
                ('special_requirements', models.TextField(blank=True, verbose_name='Особые требования')),
                ('planned_start_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Плановая дата начала')),
                ('planned_end_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Плановая дата окончания')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Назначен')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_transport_orders', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_transport_orders', to='crm.organization', verbose_name='Клиент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_orders', to='crm.organization', verbose_name='Наша компания')),
                ('package_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_orders', to='crm.packagetype', verbose_name='Вид упаковки')),
                ('transportation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_order', to='crm.transportation', verbose_name='Созданный рейс')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('-document_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TransportOrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Последний номер')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_number_sequences', to='crm.organization', verbose_name='Наша компания')),
            ],
            options={
                'verbose_name': 'нумератор заказов',
                'verbose_name_plural': 'нумераторы заказов',
            },
        ),
        migrations.CreateModel(
            name='TransportOrderStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('kind', models.CharField(choices=[('pickup', 'Погрузка'), ('delivery', 'Выгрузка')], max_length=20, verbose_name='Операция')),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('planned_time_from', models.TimeField(blank=True, null=True, verbose_name='Время с')),
                ('planned_time_to', models.TimeField(blank=True, null=True, verbose_name='Время до')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('instructions', models.TextField(blank=True, verbose_name='Инструкции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='crm.transportorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'точка маршрута заказа',
                'verbose_name_plural': 'точки маршрута заказа',
                'ordering': ('sequence',),
            },
        ),
        migrations.AddIndex(
            model_name='transportorder',
            index=models.Index(fields=['owner_company', 'status'], name='crm_transpo_owner_c_3c3b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='transportorder',
            index=models.Index(fields=['client', 'document_date'], name='crm_transpo_client__2c3be2_idx'),
        ),
        migrations.AddIndex(
            model_name='transportorder',
            index=models.Index(fields=['planned_start_date', 'planned_end_date'], name='crm_transpo_planned_58ac7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportordernumbersequence',
            constraint=models.UniqueConstraint(fields=('owner_company', 'year'), name='unique_order_sequence_per_company_year'),
        ),
        migrations.AddConstraint(
            model_name='transportorderstop',
            constraint=models.UniqueConstraint(fields=('order', 'sequence'), name='unique_transport_order_stop_sequence'),
        ),
    ]
