# Generated by Django 5.2.17 on 2026-09-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_transport_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='kind',
            field=models.CharField(choices=[('truck', 'Грузовой автомобиль'), ('tractor', 'Седельный тягач'), ('van', 'Фургон'), ('gazelle', 'Газель'), ('trailer', 'Прицеп'), ('semitrailer', 'Полуприцеп'), ('other', 'Другое')], max_length=20, verbose_name='Тип единицы'),
        ),
        migrations.CreateModel(
            name='VehicleCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combinations_as_tractor', to='crm.vehicle', verbose_name='Основной автомобиль')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combinations_as_trailer', to='crm.vehicle', verbose_name='Прицеп / полуприцеп')),
            ],
            options={
                'verbose_name': 'сцепка',
                'verbose_name_plural': 'сцепки',
                'ordering': ('-is_active', 'tractor__registration_number', 'trailer__registration_number'),
            },
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_assignments', to='crm.vehiclecombination', verbose_name='Сцепка'),
        ),
        migrations.AddConstraint(
            model_name='vehiclecombination',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tractor',), name='unique_active_combination_tractor'),
        ),
        migrations.AddConstraint(
            model_name='vehiclecombination',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('trailer',), name='unique_active_combination_trailer'),
        ),
    ]
