# Generated by Django 5.2.17 on 2026-09-02 15:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_vehicle_kind_vehiclecombination_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_term_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Отсрочка оплаты, дней'),
        ),
        migrations.AddField(
            model_name='contract',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.vatrate', verbose_name='Ставка НДС'),
        ),
        migrations.AddField(
            model_name='organization',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Кредитный лимит'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_organizations', to='crm.vatrate', verbose_name='Ставка НДС по умолчанию'),
        ),
        migrations.AddField(
            model_name='organization',
            name='edo_operator',
            field=models.CharField(blank=True, max_length=150, verbose_name='Оператор ЭДО'),
        ),
        migrations.AddField(
            model_name='organization',
            name='fns_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проверено ФНС'),
        ),
        migrations.AddField(
            model_name='organization',
            name='fns_status',
            field=models.CharField(choices=[('unknown', 'Не проверен'), ('active', 'Действует'), ('liquidated', 'Ликвидировано'), ('liquidating', 'В процессе ликвидации'), ('reorganizing', 'В процессе реорганизации'), ('bankrupt', 'Банкротство')], default='unknown', max_length=20, verbose_name='Статус ФНС'),
        ),
        migrations.AddField(
            model_name='organization',
            name='originals_handling',
            field=models.CharField(choices=[('edo', 'Только ЭДО'), ('paper', 'Бумажные оригиналы'), ('both', 'ЭДО и бумажные оригиналы')], default='both', max_length=10, verbose_name='Работа с оригиналами'),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_term_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Отсрочка оплаты, дней'),
        ),
        migrations.CreateModel(
            name='OrganizationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('fns_sync', 'Обновление из ФНС')], default='update', max_length=20, verbose_name='Действие')),
                ('changes', models.JSONField(default=dict, verbose_name='Изменения')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='crm.organization', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'изменение контрагента',
                'verbose_name_plural': 'история изменений контрагентов',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='crm_organiz_organiz_14a154_idx')],
            },
        ),
    ]
