# Generated by Django 5.2.17 on 2026-09-02 16:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_contract_document_file_contract_payment_term_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('client_penalty', 'Штраф клиенту'), ('carrier_penalty', 'Штраф перевозчику'), ('claim', 'Претензия'), ('shortage', 'Недостача'), ('damage', 'Повреждение груза'), ('delay', 'Срыв сроков'), ('idle', 'Простой'), ('extra_cost', 'Дополнительный расход')], max_length=30, verbose_name='Вид события')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('resolved', 'Закрыта'), ('cancelled', 'Отменена')], default='open', max_length=20, verbose_name='Статус')),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата события')),
                ('title', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('financial_impact', models.CharField(choices=[('none', 'Не влияет на финансы'), ('income', 'Дополнительный доход'), ('expense', 'Дополнительный расход')], default='none', max_length=10, verbose_name='Финансовый эффект')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('resolution', models.TextField(blank=True, verbose_name='Решение / результат')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='transportation-incidents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Подтверждающий документ')),
                ('resolved_on', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transportation_incidents', to='crm.organization', verbose_name='Контрагент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_transportation_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='crm.transportation', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'штраф / претензия по рейсу',
                'verbose_name_plural': 'штрафы и претензии по рейсам',
                'ordering': ('-occurred_on', '-created_at'),
                'indexes': [models.Index(fields=['transportation', 'status'], name='crm_transpo_transpo_5fb6cc_idx')],
            },
        ),
    ]
