# Generated by Django 5.2.17 on 2026-09-03 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_transportationincident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationElectronicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('ezz', 'ЭЗЗ · заказ-заявка'), ('epe', 'ЭПЭ · поручение экспедитору'), ('eer', 'ЭЭР · экспедиторская расписка'), ('etrn', 'ЭТрН · электронная транспортная накладная')], max_length=10, verbose_name='Вид ЭПД')),
                ('provider', models.CharField(choices=[('internal', 'Внутренний черновик'), ('kontur', 'Контур.Логистика'), ('saby', 'Saby (СБИС)')], default='internal', max_length=20, verbose_name='Оператор')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Подготовлен'), ('sent', 'Отправлен'), ('processing', 'Обрабатывается'), ('accepted', 'Принят'), ('accepted_with_warnings', 'Принят с предупреждениями'), ('rejected', 'Отклонён'), ('error', 'Ошибка обмена'), ('cancelled', 'Аннулирован')], default='draft', max_length=30, verbose_name='Статус')),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='Идентификатор у оператора')),
                ('external_status', models.CharField(blank=True, max_length=100, verbose_name='Статус у оператора')),
                ('title_statuses', models.JSONField(blank=True, default=dict, help_text="Например: {'1': 'draft', '2': 'signed'}.", verbose_name='Статусы титулов')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Каноническое содержимое')),
                ('raw_xml', models.TextField(blank=True, verbose_name='Сформированный XML')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_transportation_electronic_documents', to=settings.AUTH_USER_MODEL, verbose_name='Подготовил')),
                ('stop', models.ForeignKey(blank=True, help_text='Для ЭТрН указывается точка выгрузки; остальные документы относятся ко всему рейсу.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electronic_documents', to='crm.transportationstop', verbose_name='Точка маршрута')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_documents', to='crm.transportation', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'электронный перевозочный документ',
                'verbose_name_plural': 'электронные перевозочные документы',
                'ordering': ('kind', 'stop__sequence', 'created_at'),
                'indexes': [models.Index(fields=['transportation', 'kind', 'status'], name='crm_transpo_transpo_19c454_idx'), models.Index(fields=['provider', 'status'], name='crm_transpo_provide_4feee9_idx')],
                'constraints': [models.UniqueConstraint(fields=('transportation', 'kind', 'stop'), name='unique_transportation_epd_kind_stop')],
            },
        ),
    ]
