# Generated by Django 5.2.17 on 2026-09-03 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_transportationelectronicdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transportationelectronicdocument',
            name='unique_transportation_epd_kind_stop',
        ),
        migrations.AddConstraint(
            model_name='transportationelectronicdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('stop__isnull', True)), fields=('transportation', 'kind'), name='unique_transportation_epd_kind_whole_trip'),
        ),
        migrations.AddConstraint(
            model_name='transportationelectronicdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('stop__isnull', False)), fields=('transportation', 'kind', 'stop'), name='unique_transportation_epd_kind_stop'),
        ),
    ]
