# Generated by Django 5.2.17 on 2026-09-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_remove_transportationelectronicdocument_unique_transportation_epd_kind_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationelectronicdocument',
            name='operator_xml',
            field=models.TextField(blank=True, help_text='Упрощённый XML для GenerateTitleXml; итоговый титул формирует оператор ЭПД.', verbose_name='XML UserDataXml оператора'),
        ),
    ]
