# Generated by Django 5.2.17 on 2026-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_transportationelectronicdocument_operator_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='edo_id',
            field=models.CharField(blank=True, help_text='Идентификатор организации в Контур.Диадок/ЭДО (boxId или participantId).', max_length=255, verbose_name='Идентификатор участника ЭДО'),
        ),
    ]
