# Generated by Django 5.2.17 on 2026-09-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_organization_edo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationstop',
            name='address_area',
            field=models.CharField(blank=True, max_length=150, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='transportationstop',
            name='address_block',
            field=models.CharField(blank=True, max_length=30, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='transportationstop',
            name='address_city',
            field=models.CharField(blank=True, max_length=150, verbose_name='Населённый пункт'),
        ),
        migrations.AddField(
            model_name='transportationstop',
            name='address_fias_id',
            field=models.CharField(blank=True, max_length=36, verbose_name='ФИАС'),
        ),
        migrations.AddField(
            model_name='transportationstop',
            name='address_flat',
            field=models.CharField(blank=True, max_length=30, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='transportationstop',
            name='address_house',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='transportationstop',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='transportationstop',
            name='address_region',
            field=models.CharField(blank=True, max_length=150, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='transportationstop',
            name='address_region_code',
            field=models.CharField(blank=True, max_length=3, verbose_name='Код региона'),
        ),
        migrations.AddField(
            model_name='transportationstop',
            name='address_settlement',
            field=models.CharField(blank=True, max_length=150, verbose_name='Посёлок'),
        ),
        migrations.AddField(
            model_name='transportationstop',
            name='address_street',
            field=models.CharField(blank=True, max_length=150, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='address_area',
            field=models.CharField(blank=True, max_length=150, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='address_block',
            field=models.CharField(blank=True, max_length=30, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='address_city',
            field=models.CharField(blank=True, max_length=150, verbose_name='Населённый пункт'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='address_fias_id',
            field=models.CharField(blank=True, max_length=36, verbose_name='ФИАС'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='address_flat',
            field=models.CharField(blank=True, max_length=30, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='address_house',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='address_region',
            field=models.CharField(blank=True, max_length=150, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='address_region_code',
            field=models.CharField(blank=True, max_length=3, verbose_name='Код региона'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='address_settlement',
            field=models.CharField(blank=True, max_length=150, verbose_name='Посёлок'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='address_street',
            field=models.CharField(blank=True, max_length=150, verbose_name='Улица'),
        ),
    ]
