# Generated by Django 5.2.17 on 2026-09-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_transportationstop_address_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='legal_address_area',
            field=models.CharField(blank=True, max_length=150, verbose_name='Район юридического адреса'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address_block',
            field=models.CharField(blank=True, max_length=30, verbose_name='Корпус юридического адреса'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address_city',
            field=models.CharField(blank=True, max_length=150, verbose_name='Город юридического адреса'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address_fias_id',
            field=models.CharField(blank=True, max_length=36, verbose_name='ФИАС юридического адреса'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address_flat',
            field=models.CharField(blank=True, max_length=30, verbose_name='Квартира юридического адреса'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address_house',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дом юридического адреса'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address_postal_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Индекс юридического адреса'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address_region',
            field=models.CharField(blank=True, max_length=150, verbose_name='Регион юридического адреса'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address_region_code',
            field=models.CharField(blank=True, max_length=3, verbose_name='Код региона юридического адреса'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address_settlement',
            field=models.CharField(blank=True, max_length=150, verbose_name='Посёлок юридического адреса'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address_street',
            field=models.CharField(blank=True, max_length=150, verbose_name='Улица юридического адреса'),
        ),
    ]
