# Generated by Django 5.2.17 on 2026-09-03 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_organization_legal_address_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.transportation', verbose_name='Перевозка / рейс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.shipment', verbose_name='Заявка'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('shipment__isnull', False), ('transportation__isnull', True)), models.Q(('shipment__isnull', True), ('transportation__isnull', False)), _connector='OR'), name='payment_has_exactly_one_document'),
        ),
    ]
