# Generated by Django 5.2.17 on 2026-09-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_payment_transportation_alter_payment_shipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationstatusevent',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='Пары значений «было → стало» для аудита документа.', verbose_name='Изменения'),
        ),
    ]
