# Generated by Django 5.2.17 on 2026-09-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_transportationstatusevent_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationstatusevent',
            name='source',
            field=models.CharField(choices=[('document', 'Карточка рейса'), ('order', 'Заказ'), ('posting', 'Проведение'), ('unposting', 'Отмена проведения'), ('chain', 'Цепочка исполнения'), ('payment', 'Платёж'), ('incident', 'Штраф / претензия'), ('epd', 'ЭПД'), ('manual', 'Вручную')], default='manual', max_length=30, verbose_name='Источник'),
        ),
    ]
