# Generated by Django 5.2.17 on 2026-09-03 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_alter_transportationstatusevent_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Задача')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('kind', models.CharField(choices=[('manual', 'Поручение'), ('assignment', 'Назначение исполнителя'), ('document', 'Документы'), ('payment', 'Оплата'), ('control', 'Контроль рейса'), ('other', 'Другое')], default='manual', max_length=30, verbose_name='Тип')),
                ('status', models.CharField(choices=[('todo', 'Новая'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], default='todo', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=20, verbose_name='Приоритет')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнена')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planner_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_planner_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Завершил')),
                ('transportation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planner_tasks', to='crm.transportation', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'задача планировщика',
                'verbose_name_plural': 'задачи планировщика',
                'ordering': ('due_date', '-priority', '-created_at'),
                'indexes': [models.Index(fields=['status', 'due_date'], name='crm_planner_status_5c7585_idx'), models.Index(fields=['assignee', 'status'], name='crm_planner_assigne_ce2a79_idx'), models.Index(fields=['transportation', 'due_date'], name='crm_planner_transpo_6d38d2_idx')],
            },
        ),
    ]
