# Generated by Django 5.2.17 on 2026-09-04 10:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_plannertask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Номер банковского документа')),
                ('statement_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата выписки')),
                ('direction', models.CharField(choices=[('income', 'Приход от клиентов'), ('expense', 'Расход перевозчикам')], max_length=10, verbose_name='Вид операции')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён'), ('voided', 'Аннулирован')], default='draft', max_length=20, verbose_name='Статус')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Номер банковской выписки')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='crm.organizationbankaccount', verbose_name='Банковский счёт')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_bank_statements', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='crm.organization', verbose_name='Наша компания')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_bank_statements', to=settings.AUTH_USER_MODEL, verbose_name='Провёл')),
            ],
            options={
                'verbose_name': 'банковский приход / расход',
                'verbose_name_plural': 'банковские приходы / расходы',
                'ordering': ('-statement_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_line', to='crm.payment', verbose_name='Созданный платёж')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.bankstatement', verbose_name='Банковский документ')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_lines', to='crm.transportation', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'строка банковского документа',
                'verbose_name_plural': 'строки банковского документа',
            },
        ),
        migrations.CreateModel(
            name='BankStatementNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Последний номер')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_number_sequences', to='crm.organization', verbose_name='Наша компания')),
            ],
            options={
                'verbose_name': 'нумератор банковских документов',
                'verbose_name_plural': 'нумераторы банковских документов',
            },
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['owner_company', 'statement_date'], name='crm_banksta_owner_c_1c659d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['status', 'direction'], name='crm_banksta_status_3c4840_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.UniqueConstraint(fields=('statement', 'transportation'), name='unique_bank_statement_transportation'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementnumbersequence',
            constraint=models.UniqueConstraint(fields=('owner_company', 'year'), name='unique_bank_statement_sequence_per_company_year'),
        ),
    ]
