# Generated by Django 5.2.17 on 2026-09-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_bankstatement_bankstatementline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='direction',
            field=models.CharField(choices=[('income', 'Приход от клиентов'), ('expense', 'Расход перевозчикам')], default='income', max_length=10, verbose_name='Вид операции'),
        ),
    ]
