# Generated by Django 5.2.17 on 2026-09-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_alter_bankstatement_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementline',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Номер или реквизиты платёжного поручения из банковской выписки.', max_length=100, verbose_name='Платёжное поручение'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Платёжное поручение'),
        ),
    ]
