# Generated by Django 5.2.17 on 2026-09-05 10:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdocument',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_documents', to='crm.organization', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='direction',
            field=models.CharField(choices=[('outgoing', 'Исходящий'), ('incoming', 'Входящий')], default='outgoing', max_length=20, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='НДС'),
        ),
        migrations.AddIndex(
            model_name='shipmentdocument',
            index=models.Index(fields=['direction', 'kind', 'status'], name='crm_shipmen_directi_42d2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentdocument',
            index=models.Index(fields=['document_date', 'expected_date'], name='crm_shipmen_documen_1363e3_idx'),
        ),
    ]
