# Generated by Django 5.2.17 on 2026-09-05 20:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_shipmentdocument_counterparty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Номер документа')),
                ('document_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата документа')),
                ('direction', models.CharField(choices=[('outgoing', 'Исходящие клиенту'), ('incoming', 'Входящие от исполнителей')], default='outgoing', max_length=20, verbose_name='Направление')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён'), ('voided', 'Аннулирован')], default='draft', max_length=20, verbose_name='Статус')),
                ('default_kind', models.CharField(choices=[('trn', 'Транспортная накладная (ТрН)'), ('invoice', 'Счёт'), ('upd', 'УПД'), ('act', 'Акт'), ('vat_invoice', 'Счёт-фактура'), ('other', 'Другое')], default='upd', max_length=20, verbose_name='Тип документа по умолчанию')),
                ('default_status', models.CharField(choices=[('expected', 'Ожидается'), ('draft', 'Черновик'), ('issued', 'Выставлен'), ('received', 'Получен'), ('signed', 'Подписан'), ('original', 'Оригинал получен'), ('cancelled', 'Аннулирован')], default='issued', max_length=20, verbose_name='Статус строк по умолчанию')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Номер реестра / входящего пакета')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_document_batches', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_batches', to='crm.organization', verbose_name='Наша компания')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_document_batches', to=settings.AUTH_USER_MODEL, verbose_name='Провёл')),
            ],
            options={
                'verbose_name': 'пачка документов',
                'verbose_name_plural': 'пачки документов',
                'ordering': ('-document_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DocumentBatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('trn', 'Транспортная накладная (ТрН)'), ('invoice', 'Счёт'), ('upd', 'УПД'), ('act', 'Акт'), ('vat_invoice', 'Счёт-фактура'), ('other', 'Другое')], max_length=20, verbose_name='Тип документа')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='НДС')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.documentbatch', verbose_name='Пачка документов')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_batch_lines', to='crm.organization', verbose_name='Контрагент')),
                ('shipment_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_batch_line', to='crm.shipmentdocument', verbose_name='Запись реестра')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_batch_lines', to='crm.transportation', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'строка пачки документов',
                'verbose_name_plural': 'строки пачки документов',
            },
        ),
        migrations.CreateModel(
            name='DocumentBatchNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Последний номер')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_batch_number_sequences', to='crm.organization', verbose_name='Наша компания')),
            ],
            options={
                'verbose_name': 'нумератор пачек документов',
                'verbose_name_plural': 'нумераторы пачек документов',
            },
        ),
        migrations.AddIndex(
            model_name='documentbatch',
            index=models.Index(fields=['owner_company', 'document_date'], name='crm_documen_owner_c_68ea87_idx'),
        ),
        migrations.AddIndex(
            model_name='documentbatch',
            index=models.Index(fields=['status', 'direction'], name='crm_documen_status_f3783f_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentbatchline',
            constraint=models.UniqueConstraint(fields=('batch', 'transportation', 'kind'), name='unique_document_batch_transportation_kind'),
        ),
        migrations.AddConstraint(
            model_name='documentbatchnumbersequence',
            constraint=models.UniqueConstraint(fields=('owner_company', 'year'), name='unique_document_batch_sequence_per_company_year'),
        ),
    ]
