# Generated by Django 5.2.17 on 2026-09-05 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_documentbatch_documentbatchline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdocument',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.transportation', verbose_name='Рейс'),
        ),
        migrations.AlterField(
            model_name='shipmentdocument',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.shipment', verbose_name='Заявка'),
        ),
    ]
