# Generated by Django 5.2.17 on 2026-09-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_shipmentdocument_transportation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationstop',
            name='organization_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование организации вручную'),
        ),
    ]
