# Generated by Django 5.2.17 on 2026-09-09 22:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_transportationstop_organization_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Номер акта')),
                ('document_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата акта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('generated', 'Сформирован'), ('voided', 'Аннулирован')], default='draft', max_length=20, verbose_name='Статус')),
                ('period_from', models.DateField(verbose_name='Период с')),
                ('period_to', models.DateField(verbose_name='Период по')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сальдо на начало')),
                ('debit_turnover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Дебетовый оборот')),
                ('credit_turnover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Кредитовый оборот')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сальдо на конец')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_reconciliation_acts', to='crm.organization', verbose_name='Контрагент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_reconciliation_acts', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_reconciliation_acts', to=settings.AUTH_USER_MODEL, verbose_name='Сформировал')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_acts', to='crm.organization', verbose_name='Наша компания')),
            ],
            options={
                'verbose_name': 'акт сверки',
                'verbose_name_plural': 'акты сверки',
                'ordering': ('-document_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ReconciliationActLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('movement_date', models.DateField(verbose_name='Дата')),
                ('description', models.CharField(max_length=255, verbose_name='Содержание операции')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Дебет')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Кредит')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сальдо')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.reconciliationact', verbose_name='Акт сверки')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_lines', to='crm.settlementmovement', verbose_name='Движение взаиморасчётов')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_lines', to='crm.transportation', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'строка акта сверки',
                'verbose_name_plural': 'строки акта сверки',
                'ordering': ('movement_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ReconciliationActNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Последний номер')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_number_sequences', to='crm.organization', verbose_name='Наша компания')),
            ],
            options={
                'verbose_name': 'нумератор актов сверки',
                'verbose_name_plural': 'нумераторы актов сверки',
            },
        ),
        migrations.AddIndex(
            model_name='reconciliationact',
            index=models.Index(fields=['owner_company', 'counterparty', 'period_from', 'period_to'], name='crm_reconci_owner_c_2459c6_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationact',
            index=models.Index(fields=['status', 'document_date'], name='crm_reconci_status_8d8c14_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationactline',
            constraint=models.UniqueConstraint(fields=('act', 'movement'), name='unique_reconciliation_act_movement'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationactnumbersequence',
            constraint=models.UniqueConstraint(fields=('owner_company', 'year'), name='unique_reconciliation_sequence_per_company_year'),
        ),
    ]
