# Generated by Django 5.2.17 on 2026-09-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_reconciliationact_reconciliationactline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_categories',
            field=models.CharField(blank=True, help_text='Например: B, C, CE', max_length=100, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Удостоверение действительно до'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Номер водительского удостоверения'),
        ),
    ]
