# Generated by Django 5.2.17 on 2026-09-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_driver_license_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('client_instruction_received', 'Поручение клиента получено'), ('executor_search', 'Поиск исполнителя'), ('executor_selected', 'Назначен исполнитель'), ('executor_documents_verified', 'Документы исполнителя проверены'), ('vehicle_confirmed', 'Машина подтверждена'), ('loading', 'На погрузке'), ('in_transit', 'В пути'), ('unloading', 'На выгрузке'), ('delivered', 'Доставлено'), ('documents_received', 'Документы получены'), ('documents_sent', 'Документы отправлены'), ('document_flow_completed', 'Документооборот завершён'), ('customer_invoiced', 'Выставлено клиенту'), ('closed', 'Закрыто'), ('on_hold', 'Приостановлено'), ('cancelled', 'Отменено')], default='new', max_length=40, verbose_name='Статус'),
        ),
    ]
