# Generated by Django 5.2.17 on 2026-09-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_merge_package_and_pallet_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='adr_class',
            field=models.CharField(blank=True, max_length=3, verbose_name='Класс опасности ADR'),
        ),
        migrations.AddField(
            model_name='transportorder',
            name='adr_class',
            field=models.CharField(blank=True, choices=[('', 'Не относится к опасным грузам'), ('1', 'Класс 1 — Взрывчатые вещества и изделия'), ('2.1', 'Класс 2.1 — Воспламеняющиеся газы'), ('2.2', 'Класс 2.2 — Невоспламеняющиеся нетоксичные газы'), ('2.3', 'Класс 2.3 — Токсичные газы'), ('3', 'Класс 3 — Легковоспламеняющиеся жидкости'), ('4.1', 'Класс 4.1 — Легковоспламеняющиеся твёрдые вещества'), ('4.2', 'Класс 4.2 — Самовозгорающиеся вещества'), ('4.3', 'Класс 4.3 — Вещества, выделяющие горючие газы при контакте с водой'), ('5.1', 'Класс 5.1 — Окисляющие вещества'), ('5.2', 'Класс 5.2 — Органические пероксиды'), ('6.1', 'Класс 6.1 — Токсичные вещества'), ('6.2', 'Класс 6.2 — Инфекционные вещества'), ('7', 'Класс 7 — Радиоактивные материалы'), ('8', 'Класс 8 — Коррозионные вещества'), ('9', 'Класс 9 — Прочие опасные вещества и изделия')], max_length=3, verbose_name='Класс опасности ADR'),
        ),
        migrations.AlterField(
            model_name='transportorder',
            name='payment_form',
            field=models.CharField(choices=[('bank_vat_5', 'Безналичный расчёт · НДС 5%'), ('bank_vat_7', 'Безналичный расчёт · НДС 7%'), ('bank_vat_10', 'Безналичный расчёт · НДС 10%'), ('bank_vat_20', 'Безналичный расчёт · НДС 20%'), ('bank_vat_22', 'Безналичный расчёт · НДС 22%'), ('bank_with_vat', 'Безналичный расчёт · НДС'), ('bank_without_vat', 'Безналичный расчёт · Без НДС'), ('cash', 'Наличный расчёт')], default='bank_with_vat', max_length=30, verbose_name='Форма оплаты'),
        ),
        migrations.AlterField(
            model_name='transportorder',
            name='temperature_regime',
            field=models.CharField(blank=True, default='Отсутствует', max_length=100, verbose_name='Температурный режим'),
        ),
    ]
