# Generated by Django 5.2.17 on 2026-09-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_transportation_adr_class_transportorder_adr_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_payment_form',
            field=models.CharField(blank=True, choices=[('bank_vat_5', 'Безналичный расчёт · НДС 5%'), ('bank_vat_7', 'Безналичный расчёт · НДС 7%'), ('bank_vat_10', 'Безналичный расчёт · НДС 10%'), ('bank_vat_20', 'Безналичный расчёт · НДС 20%'), ('bank_vat_22', 'Безналичный расчёт · НДС 22%'), ('bank_with_vat', 'Безналичный расчёт · НДС'), ('bank_without_vat', 'Безналичный расчёт · Без НДС'), ('cash', 'Наличный расчёт')], max_length=30, verbose_name='Форма оплаты по умолчанию'),
        ),
    ]
