# Generated by Django 5.2.17 on 2026-09-11 19:14

from django.db import migrations, models


def normalize_payment_forms(apps, schema_editor):
    """Keep existing orders and counterparties on a visible current value."""
    TransportOrder = apps.get_model("crm", "TransportOrder")
    Organization = apps.get_model("crm", "Organization")
    TransportOrder.objects.filter(payment_form="bank_with_vat").update(
        payment_form="bank_vat_22"
    )
    TransportOrder.objects.filter(payment_form="bank_without_vat").update(
        payment_form="bank_not_taxable"
    )
    Organization.objects.filter(default_payment_form="bank_with_vat").update(
        default_payment_form="bank_vat_22"
    )
    Organization.objects.filter(default_payment_form="bank_without_vat").update(
        default_payment_form="bank_not_taxable"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_organization_default_payment_form'),
    ]

    operations = [
        migrations.RunPython(normalize_payment_forms, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organization',
            name='default_payment_form',
            field=models.CharField(blank=True, choices=[('bank_vat_0', 'НДС 0%'), ('bank_vat_5', 'НДС 5%'), ('bank_vat_7', 'НДС 7%'), ('bank_vat_10', 'НДС 10%'), ('bank_vat_18', 'НДС 18%'), ('bank_vat_20', 'НДС 20%'), ('bank_vat_22', 'НДС 22%'), ('bank_not_taxable', 'НДС не облагается'), ('cash', 'Наличные')], max_length=30, verbose_name='Форма оплаты по умолчанию'),
        ),
        migrations.AlterField(
            model_name='transportorder',
            name='payment_form',
            field=models.CharField(choices=[('bank_vat_0', 'НДС 0%'), ('bank_vat_5', 'НДС 5%'), ('bank_vat_7', 'НДС 7%'), ('bank_vat_10', 'НДС 10%'), ('bank_vat_18', 'НДС 18%'), ('bank_vat_20', 'НДС 20%'), ('bank_vat_22', 'НДС 22%'), ('bank_not_taxable', 'НДС не облагается'), ('cash', 'Наличные')], default='bank_vat_22', max_length=30, verbose_name='Форма оплаты'),
        ),
    ]
