# Generated by Django 5.2.17 on 2026-09-11 22:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_alter_organization_default_payment_form_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('notification_key', models.CharField(max_length=255, verbose_name='Ключ уведомления')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Прочитано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notification_reads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'прочитанное уведомление',
                'verbose_name_plural': 'прочитанные уведомления',
                'constraints': [models.UniqueConstraint(fields=('user', 'notification_key'), name='unique_user_notification_read')],
            },
        ),
    ]
