# Generated by Django 5.2.17 on 2026-09-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportorderstop',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_order_stops', to='crm.organization', verbose_name='Организация точки маршрута'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='organization_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование организации вручную'),
        ),
    ]
