# Generated by Django 5.2.17 on 2026-09-13

from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0056_add_order_stop_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportorder",
            name="cargo_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[MinValueValidator(Decimal("0"))],
                verbose_name="Стоимость груза",
            ),
        ),
    ]
