# Generated by Django 5.2.17 on 2026-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_transportorder_cargo_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='acting_basis',
            field=models.CharField(blank=True, max_length=255, verbose_name='Действует на основании'),
        ),
        migrations.AddField(
            model_name='organization',
            name='director_position',
            field=models.CharField(blank=True, max_length=150, verbose_name='Должность руководителя'),
        ),
    ]
