# Generated by Django 5.2.17 on 2026-09-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_organization_director_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_term_basis',
            field=models.CharField(choices=[('delivery_date', 'Дата доставки'), ('document_date', 'Дата документа'), ('originals_received', 'Получение оригиналов')], default='delivery_date', max_length=30, verbose_name='Основание срока оплаты'),
        ),
    ]
