# Generated by Django 5.2 on 2026-09-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0059_organization_payment_term_basis"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationRequisiteChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("effective_date", models.DateField(verbose_name="Дата изменения")),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("kind", "Вид контрагента"),
                            ("short_name", "Наименование"),
                            ("name", "Полное наименование"),
                            ("tax_id", "ИНН"),
                            ("kpp", "КПП"),
                            ("ogrn", "ОГРН / ОГРНИП"),
                            ("registration_date", "Дата регистрации"),
                            ("legal_address", "Юридический адрес"),
                            ("director_position", "Должность руководителя"),
                            ("director_name", "Ф. И. О. руководителя"),
                            ("acting_basis", "Действует на основании"),
                        ],
                        max_length=40,
                        verbose_name="Реквизит",
                    ),
                ),
                ("new_value", models.CharField(max_length=500, verbose_name="Что изменилось")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisite_changes",
                        to="crm.organization",
                        verbose_name="Контрагент",
                    ),
                ),
            ],
            options={
                "verbose_name": "изменение реквизита контрагента",
                "verbose_name_plural": "изменения реквизитов контрагента",
                "ordering": ("-effective_date", "-pk"),
            },
        ),
        migrations.AddIndex(
            model_name="organizationrequisitechange",
            index=models.Index(
                fields=["organization", "-effective_date"],
                name="crm_organiz_organiz_6de8c2_idx",
            ),
        ),
    ]
