# Generated by Django 5.2.17 on 2026-09-14 10:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def copy_order_payment_terms(apps, schema_editor):
    Transportation = apps.get_model("crm", "Transportation")
    for transportation in Transportation.objects.filter(
        source_order__isnull=False
    ).select_related("source_order"):
        order = transportation.source_order
        updates = {"customer_payment_form": order.payment_form}
        if not transportation.client_reference:
            updates["client_reference"] = order.number
        Transportation.objects.filter(pk=transportation.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_organizationrequisitechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='customer_payment_form',
            field=models.CharField(choices=[('bank_vat_0', 'НДС 0%'), ('bank_vat_5', 'НДС 5%'), ('bank_vat_7', 'НДС 7%'), ('bank_vat_10', 'НДС 10%'), ('bank_vat_18', 'НДС 18%'), ('bank_vat_20', 'НДС 20%'), ('bank_vat_22', 'НДС 22%'), ('bank_not_taxable', 'НДС не облагается'), ('cash', 'Наличные')], default='bank_vat_22', max_length=30, verbose_name='Форма оплаты клиента'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='customer_prepayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Предоплата клиента'),
        ),
        migrations.RunPython(copy_order_payment_terms, migrations.RunPython.noop),
    ]
