# Generated by Django 5.2.17 on 2026-09-14 10:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_normalize_transportation_client_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='customer_prepayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Предоплата клиента'),
        ),
    ]
