# Generated by Django 5.2.17 on 2026-09-14 10:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_make_transportation_prepayment_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportorder',
            name='prepayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Предоплата'),
        ),
    ]
