# Generated by Django 5.2.17 on 2026-09-14 10:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_add_order_prepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='executor_payment_form',
            field=models.CharField(choices=[('bank_vat_0', 'НДС 0%'), ('bank_vat_5', 'НДС 5%'), ('bank_vat_7', 'НДС 7%'), ('bank_vat_10', 'НДС 10%'), ('bank_vat_18', 'НДС 18%'), ('bank_vat_20', 'НДС 20%'), ('bank_vat_22', 'НДС 22%'), ('bank_not_taxable', 'НДС не облагается'), ('cash', 'Наличные')], default='bank_vat_22', max_length=30, verbose_name='Форма оплаты исполнителю'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='executor_prepayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Предоплата исполнителю'),
        ),
    ]
