# Generated by Django 5.2.17 on 2026-09-14 10:34

from django.db import migrations, models


def copy_existing_executor_terms(apps, schema_editor):
    Transportation = apps.get_model("crm", "Transportation")
    for transportation in Transportation.objects.all().only(
        "pk", "currency", "payment_due_basis"
    ):
        Transportation.objects.filter(pk=transportation.pk).update(
            executor_currency=transportation.currency,
            executor_payment_due_basis=transportation.payment_due_basis,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_add_executor_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='executor_currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта исполнителя'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='executor_payment_due_basis',
            field=models.CharField(choices=[('delivery_date', 'Дата доставки'), ('document_date', 'Дата документа'), ('originals_received', 'Получение оригиналов')], default='delivery_date', max_length=30, verbose_name='Основание срока оплаты исполнителю'),
        ),
        migrations.RunPython(copy_existing_executor_terms, migrations.RunPython.noop),
    ]
