# Generated by Django 5.2.17 on 2026-09-14 10:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def copy_source_order_cargo_values(apps, schema_editor):
    Transportation = apps.get_model("crm", "Transportation")
    for transportation in Transportation.objects.filter(
        source_order__isnull=False
    ).select_related("source_order"):
        Transportation.objects.filter(pk=transportation.pk).update(
            cargo_value=transportation.source_order.cargo_value
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0066_split_executor_currency_and_due_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='cargo_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Стоимость груза'),
        ),
        migrations.RunPython(copy_source_order_cargo_values, migrations.RunPython.noop),
    ]
