# Generated by Django 5.2.17 on 2026-09-14 13:37

import django.db.models.deletion
from django.db import migrations, models


def fill_existing_order_terms(apps, schema_editor):
    Contract = apps.get_model("crm", "Contract")
    TransportOrder = apps.get_model("crm", "TransportOrder")
    for order in TransportOrder.objects.select_related("client", "owner_company"):
        contract = Contract.objects.filter(
            kind="client_forwarding",
            customer__organization_id=order.client_id,
            expeditor__organization_id=order.owner_company_id,
            status__in=["ready", "signed"],
        ).order_by("-status", "-contract_date", "-pk").first()
        TransportOrder.objects.filter(pk=order.pk).update(
            customer_contract_id=contract.pk if contract else None,
            payment_due_basis=order.client.payment_term_basis or "delivery_date",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_transportation_cargo_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportorder',
            name='customer_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_orders', to='crm.contract', verbose_name='Договор с клиентом'),
        ),
        migrations.AddField(
            model_name='transportorder',
            name='payment_due_basis',
            field=models.CharField(choices=[('delivery_date', 'Дата доставки'), ('document_date', 'Дата документа'), ('originals_received', 'Получение оригиналов')], default='delivery_date', max_length=30, verbose_name='Основание срока оплаты'),
        ),
        migrations.RunPython(fill_existing_order_terms, migrations.RunPython.noop),
    ]
