# Generated by Django 5.2.17 on 2026-09-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_transportorder_customer_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='client_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_contact_transportations', to='crm.organizationcontact', verbose_name='Ответственный менеджер клиента'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='executor_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_contact_transportations', to='crm.organizationcontact', verbose_name='Ответственный менеджер исполнителя'),
        ),
    ]
