# Generated by Codex on 2026-09-15

import django.db.models.deletion
from django.db import migrations, models


def backfill_stop_handling_method(apps, schema_editor):
    CargoHandlingMethod = apps.get_model("crm", "CargoHandlingMethod")
    TransportOrderStop = apps.get_model("crm", "TransportOrderStop")
    TransportationStop = apps.get_model("crm", "TransportationStop")

    rear_method, _ = CargoHandlingMethod.objects.get_or_create(
        name="Задняя",
        defaults={"is_active": True},
    )
    TransportOrderStop.objects.filter(handling_method__isnull=True).update(
        handling_method=rear_method
    )
    TransportationStop.objects.filter(handling_method__isnull=True).update(
        handling_method=rear_method
    )


def clear_stop_handling_method(apps, schema_editor):
    TransportOrderStop = apps.get_model("crm", "TransportOrderStop")
    TransportationStop = apps.get_model("crm", "TransportationStop")

    TransportOrderStop.objects.update(handling_method=None)
    TransportationStop.objects.update(handling_method=None)


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0069_transportation_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportorderstop",
            name="handling_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transport_order_stops",
                to="crm.cargohandlingmethod",
                verbose_name="Вид погрузки / выгрузки",
            ),
        ),
        migrations.AddField(
            model_name="transportationstop",
            name="handling_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transportation_stops",
                to="crm.cargohandlingmethod",
                verbose_name="Вид погрузки / выгрузки",
            ),
        ),
        migrations.RunPython(
            backfill_stop_handling_method,
            clear_stop_handling_method,
        ),
    ]
