# Generated by Django 5.2.17 on 2026-09-15 20:06

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_driver_phones(apps, schema_editor):
    Driver = apps.get_model("crm", "Driver")
    DriverPhone = apps.get_model("crm", "DriverPhone")
    DriverPhone.objects.bulk_create(
        [
            DriverPhone(driver_id=driver.pk, phone=driver.phone, is_primary=True)
            for driver in Driver.objects.exclude(phone="")
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0070_add_stop_handling_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной номер')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='crm.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'телефон водителя',
                'verbose_name_plural': 'телефоны водителя',
                'ordering': ('-is_primary', 'phone'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('driver',), name='unique_primary_phone_per_driver')],
            },
        ),
        migrations.RunPython(copy_legacy_driver_phones, migrations.RunPython.noop),
    ]
