# Generated by Django 5.2.17 on 2026-09-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0071_add_driver_phone_register'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='driverpassport',
            name='unique_driver_passport_identity',
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='country',
            field=models.CharField(choices=[('RU', 'Россия'), ('BY', 'Беларусь'), ('KZ', 'Казахстан'), ('KG', 'Кыргызстан'), ('AM', 'Армения'), ('UZ', 'Узбекистан'), ('TJ', 'Таджикистан'), ('AZ', 'Азербайджан'), ('MD', 'Молдова'), ('OTHER', 'Другая страна')], default='RU', max_length=10, verbose_name='Страна документа'),
        ),
        migrations.AddField(
            model_name='driverpassport',
            name='country',
            field=models.CharField(choices=[('RU', 'Россия'), ('BY', 'Беларусь'), ('KZ', 'Казахстан'), ('KG', 'Кыргызстан'), ('AM', 'Армения'), ('UZ', 'Узбекистан'), ('TJ', 'Таджикистан'), ('AZ', 'Азербайджан'), ('MD', 'Молдова'), ('OTHER', 'Другая страна')], default='RU', max_length=10, verbose_name='Страна документа'),
        ),
        migrations.AlterField(
            model_name='driverpassport',
            name='number',
            field=models.CharField(max_length=30, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='driverpassport',
            name='series',
            field=models.CharField(max_length=30, verbose_name='Серия'),
        ),
        migrations.AddConstraint(
            model_name='driverpassport',
            constraint=models.UniqueConstraint(fields=('country', 'series', 'number'), name='unique_driver_passport_identity', violation_error_message='Водитель с такой серией и номером паспорта уже существует.'),
        ),
    ]
