# Generated by Django 5.2.17 on 2026-09-17 09:54

import django.db.models.deletion
from django.db import migrations, models


def copy_primary_carriers(apps, schema_editor):
    Vehicle = apps.get_model("crm", "Vehicle")
    VehicleCarrier = apps.get_model("crm", "VehicleCarrier")
    VehicleCarrier.objects.bulk_create(
        [
            VehicleCarrier(
                vehicle_id=vehicle_id,
                carrier_id=carrier_id,
                is_primary=True,
                is_active=True,
            )
            for vehicle_id, carrier_id in Vehicle.objects.values_list("id", "carrier_id")
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_remove_driverpassport_unique_driver_passport_identity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контрагент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображается')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_links', to='crm.carrier', verbose_name='Контрагент')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_links', to='crm.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'контрагент транспортного средства',
                'verbose_name_plural': 'контрагенты транспортных средств',
                'ordering': ('-is_primary', 'carrier__name'),
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='carriers',
            field=models.ManyToManyField(related_name='associated_vehicles', through='crm.VehicleCarrier', to='crm.carrier', verbose_name='Контрагенты'),
        ),
        migrations.RunPython(copy_primary_carriers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='vehiclecarrier',
            constraint=models.UniqueConstraint(fields=('vehicle', 'carrier'), name='unique_vehicle_carrier'),
        ),
        migrations.AddConstraint(
            model_name='vehiclecarrier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('vehicle',), name='unique_primary_vehicle_carrier'),
        ),
    ]
