# Generated by Django 5.2.17 on 2026-09-21 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_vehicle_multiple_carriers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='auto_renewal',
            field=models.BooleanField(default=False, verbose_name='Автоматическая пролонгация'),
        ),
        migrations.AddField(
            model_name='contract',
            name='counterparty_authority_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доверенности контрагента'),
        ),
        migrations.AddField(
            model_name='contract',
            name='counterparty_authority_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер доверенности контрагента'),
        ),
        migrations.AddField(
            model_name='contract',
            name='counterparty_authority_type',
            field=models.CharField(choices=[('charter', 'Устав'), ('power_of_attorney', 'Доверенность'), ('decision', 'Решение'), ('order', 'Приказ'), ('other', 'Другой документ')], default='charter', max_length=30, verbose_name='Вид основания полномочий контрагента'),
        ),
        migrations.AddField(
            model_name='contract',
            name='counterparty_representative_position',
            field=models.CharField(blank=True, max_length=150, verbose_name='Должность представителя контрагента'),
        ),
        migrations.AddField(
            model_name='contract',
            name='effective_from',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала действия'),
        ),
        migrations.AddField(
            model_name='contract',
            name='expeditor_authority_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доверенности нашей компании'),
        ),
        migrations.AddField(
            model_name='contract',
            name='expeditor_authority_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер доверенности нашей компании'),
        ),
        migrations.AddField(
            model_name='contract',
            name='expeditor_authority_type',
            field=models.CharField(choices=[('charter', 'Устав'), ('power_of_attorney', 'Доверенность'), ('decision', 'Решение'), ('order', 'Приказ'), ('other', 'Другой документ')], default='charter', max_length=30, verbose_name='Вид основания полномочий нашей компании'),
        ),
        migrations.AddField(
            model_name='contract',
            name='expeditor_representative_position',
            field=models.CharField(blank=True, max_length=150, verbose_name='Должность представителя нашей компании'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_indefinite',
            field=models.BooleanField(default=False, verbose_name='Бессрочный'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основной договор'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_day_type',
            field=models.CharField(choices=[('calendar', 'Календарные дни'), ('working', 'Рабочие дни'), ('banking', 'Банковские дни')], default='calendar', max_length=20, verbose_name='Вид отсрочки'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_trigger',
            field=models.CharField(choices=[('unloading', 'Дата выгрузки'), ('delivery_date', 'Дата доставки'), ('originals_received', 'Получение оригиналов документов'), ('scans_received', 'Получение сканов документов'), ('invoice_date', 'Выставление счёта'), ('act_signed', 'Подписание акта'), ('other', 'Другое событие')], default='delivery_date', max_length=30, verbose_name='Отсчёт срока оплаты от'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_trigger_other',
            field=models.CharField(blank=True, max_length=255, verbose_name='Другое событие оплаты'),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_months',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Срок пролонгации, месяцев'),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_notice_days',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Срок уведомления о расторжении, дней'),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина расторжения'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='customer_contract_date_snapshot',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора с клиентом на момент оформления'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='customer_contract_number_snapshot',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер договора с клиентом на момент оформления'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='customer_payment_day_type_snapshot',
            field=models.CharField(blank=True, choices=[('calendar', 'Календарные дни'), ('working', 'Рабочие дни'), ('banking', 'Банковские дни')], max_length=20, verbose_name='Вид отсрочки клиента на момент оформления'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='customer_payment_trigger_snapshot',
            field=models.CharField(blank=True, choices=[('unloading', 'Дата выгрузки'), ('delivery_date', 'Дата доставки'), ('originals_received', 'Получение оригиналов документов'), ('scans_received', 'Получение сканов документов'), ('invoice_date', 'Выставление счёта'), ('act_signed', 'Подписание акта'), ('other', 'Другое событие')], max_length=30, verbose_name='Событие оплаты клиента на момент оформления'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='executor_contract_date_snapshot',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора с исполнителем на момент оформления'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='executor_contract_number_snapshot',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер договора с исполнителем на момент оформления'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='executor_payment_day_type_snapshot',
            field=models.CharField(blank=True, choices=[('calendar', 'Календарные дни'), ('working', 'Рабочие дни'), ('banking', 'Банковские дни')], max_length=20, verbose_name='Вид отсрочки исполнителя на момент оформления'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='executor_payment_trigger_snapshot',
            field=models.CharField(blank=True, choices=[('unloading', 'Дата выгрузки'), ('delivery_date', 'Дата доставки'), ('originals_received', 'Получение оригиналов документов'), ('scans_received', 'Получение сканов документов'), ('invoice_date', 'Выставление счёта'), ('act_signed', 'Подписание акта'), ('other', 'Другое событие')], max_length=30, verbose_name='Событие оплаты исполнителя на момент оформления'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', False), ('is_primary', True)), fields=('expeditor', 'customer', 'kind'), name='unique_primary_customer_contract'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('carrier__isnull', False), ('is_primary', True)), fields=('expeditor', 'carrier', 'kind'), name='unique_primary_carrier_contract'),
        ),
    ]
