# Generated by Django 5.2.17 on 2026-09-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0074_contract_auto_renewal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='ОГРН / ОГРНИП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='VIN'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['last_name', 'first_name'], name='crm_driver_last_na_143dea_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['phone'], name='crm_driver_phone_5c5032_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_active', 'updated_at'], name='crm_driver_is_acti_c3298e_idx'),
        ),
        migrations.AddIndex(
            model_name='driverpassport',
            index=models.Index(fields=['series', 'number'], name='crm_driverp_series_474f69_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['short_name'], name='crm_organiz_short_n_513374_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['phone'], name='crm_organiz_phone_f1c20b_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'updated_at'], name='crm_organiz_is_acti_4ae373_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active', 'kind'], name='crm_vehicle_is_acti_5a8c12_idx'),
        ),
    ]
