# Generated by Django 5.2.17 on 2026-09-21 18:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_existing_documents(apps, schema_editor):
    ShipmentDocument = apps.get_model("crm", "ShipmentDocument")
    ShipmentDocumentLine = apps.get_model("crm", "ShipmentDocumentLine")
    for document in ShipmentDocument.objects.select_related("transportation").iterator():
        updates = []
        if not document.crm_number:
            document.crm_number = document.number or f"CRM-{document.pk:06d}"
            updates.append("crm_number")
        if document.transportation_id:
            document.owner_company_id = document.transportation.owner_company_id
            updates.append("owner_company")
            total = document.amount or Decimal("0.00")
            vat = document.vat_amount or Decimal("0.00")
            ShipmentDocumentLine.objects.get_or_create(
                document_id=document.pk,
                transportation_id=document.transportation_id,
                defaults={
                    "service_name": (
                        "Организация транспортных услуг по маршруту "
                        f"{document.transportation.route if hasattr(document.transportation, 'route') else document.transportation.number}"
                    ),
                    "quantity": Decimal("1.000"),
                    "unit": "услуга",
                    "price": total - vat,
                    "amount": total - vat,
                    "vat_amount": vat,
                    "total_amount": total,
                    "position": 1,
                },
            )
        if updates:
            document.save(update_fields=updates)


def reverse_existing_documents(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0075_alter_organization_email_alter_organization_ogrn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(default='Основные', max_length=100, verbose_name='Название настройки')),
                ('service_name_template', models.TextField(default='Организация транспортных услуг по маршруту {route}, водитель {driver}, ТС {vehicle}, полуприцеп {trailer}, загрузка {pickup_date} — выгрузка {delivery_date}, заказ №{order_number}.', verbose_name='Шаблон наименования услуги')),
                ('upd_max_days_after_delivery', models.PositiveSmallIntegerField(default=5, verbose_name='Максимум дней после выгрузки для УПД')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
            ],
            options={
                'verbose_name': 'настройка бухгалтерского блока',
                'verbose_name_plural': 'настройки бухгалтерского блока',
            },
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='based_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_documents', to='crm.shipmentdocument', verbose_name='Создан на основании'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина аннулирования'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Аннулирован'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_shipment_documents', to=settings.AUTH_USER_MODEL, verbose_name='Аннулировал'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_documents', to='crm.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='crm_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Внутренний номер CRM'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='one_c_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа в 1С'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='one_c_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Номер документа в 1С'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='one_c_status',
            field=models.CharField(choices=[('not_sent', 'Не передан'), ('exported', 'Передан бухгалтеру'), ('posted', 'Проведён в 1С'), ('error', 'Ошибка синхронизации')], default='not_sent', max_length=20, verbose_name='Состояние в 1С'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='one_c_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Синхронизировано с 1С'),
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_documents', to='crm.organization', verbose_name='Наша компания'),
        ),
        migrations.CreateModel(
            name='ShipmentDocumentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('action', models.CharField(choices=[('created', 'Создан'), ('updated', 'Изменён'), ('exported', 'Передан бухгалтеру'), ('imported', 'Получен номер из 1С'), ('cancelled', 'Аннулирован')], max_length=20, verbose_name='Действие')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Изменения')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='crm.shipmentdocument', verbose_name='Документ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_document_audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'изменение бухгалтерского документа',
                'verbose_name_plural': 'история бухгалтерских документов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('service_name', models.TextField(verbose_name='Наименование услуги')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, verbose_name='Количество')),
                ('unit', models.CharField(default='услуга', max_length=30, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Цена')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма без НДС')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Ставка НДС, %')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма НДС')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма с НДС')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.shipmentdocument', verbose_name='Документ')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_document_lines', to='crm.transportation', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'строка бухгалтерского документа',
                'verbose_name_plural': 'строки бухгалтерского документа',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.RunPython(migrate_existing_documents, reverse_existing_documents),
        migrations.AddField(
            model_name='shipmentdocument',
            name='transportations',
            field=models.ManyToManyField(blank=True, related_name='accounting_documents', through='crm.ShipmentDocumentLine', to='crm.transportation', verbose_name='Рейсы документа'),
        ),
        migrations.AddIndex(
            model_name='shipmentdocument',
            index=models.Index(fields=['owner_company', 'document_date'], name='crm_shipmen_owner_c_25dce8_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentdocument',
            index=models.Index(fields=['one_c_status', 'one_c_number'], name='crm_shipmen_one_c_s_3bc904_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdocumentline',
            constraint=models.UniqueConstraint(fields=('document', 'transportation'), name='unique_accounting_document_transportation'),
        ),
    ]
