# Generated by Django 5.2.17 on 2026-09-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0076_accountingsettings_shipmentdocument_based_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_data_export_override',
            field=models.BooleanField(blank=True, help_text='Пусто — использовать право, заданное ролью.', null=True, verbose_name='Экспорт персональных данных'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_data_manage_override',
            field=models.BooleanField(blank=True, help_text='Пусто — использовать право, заданное ролью.', null=True, verbose_name='Изменение персональных данных'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_data_view_override',
            field=models.BooleanField(blank=True, help_text='Пусто — использовать право, заданное ролью.', null=True, verbose_name='Просмотр персональных данных'),
        ),
    ]
