# Generated by Django 5.2.17 on 2026-09-22 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0077_userprofile_personal_data_export_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Просмотр'), ('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('export', 'Экспорт')], max_length=20, verbose_name='Действие')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_data_access_logs', to='crm.driver', verbose_name='Водитель')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_data_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'событие доступа к персональным данным',
                'verbose_name_plural': 'события доступа к персональным данным',
                'ordering': ('-created_at',),
            },
        ),
    ]
