# Generated by Django 5.2.17 on 2026-09-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0078_personaldataaccesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='crm.carrier', verbose_name='Перевозчик'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='crm.carrier', verbose_name='Перевозчик'),
        ),
    ]
