# Generated by Django 5.2.17 on 2026-09-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0079_optional_resource_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='legal_address_raw',
            field=models.JSONField(blank=True, default=dict, verbose_name='Исходный адрес DaData'),
        ),
        migrations.AddField(
            model_name='transportationstop',
            name='address_raw',
            field=models.JSONField(blank=True, default=dict, verbose_name='Исходный адрес DaData'),
        ),
        migrations.AddField(
            model_name='transportorderstop',
            name='address_raw',
            field=models.JSONField(blank=True, default=dict, verbose_name='Исходный адрес DaData'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='transportationstop',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='transportationstop',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='transportorderstop',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='transportorderstop',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
    ]
