# Generated by Django 5.2.17 on 2026-09-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0080_structured_address_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='legal_address',
            field=models.TextField(verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Адрес выгрузки'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pickup_address',
            field=models.TextField(blank=True, verbose_name='Адрес погрузки'),
        ),
    ]
