# Generated by Django 5.2.17 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0081_long_legacy_addresses"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contract",
            name="unique_contract_number_per_expeditor",
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("customer__isnull", False)),
                fields=("expeditor", "customer", "number"),
                name="unique_contract_number_per_customer_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("carrier__isnull", False)),
                fields=("expeditor", "carrier", "number"),
                name="unique_contract_number_per_carrier_pair",
            ),
        ),
    ]
