# Generated by Django 5.2.17 on 2026-09-25 19:20

from django.db import migrations, models


def preserve_existing_payment_triggers(apps, schema_editor):
    Organization = apps.get_model("crm", "Organization")
    trigger_by_legacy_basis = {
        "originals_received": "originals_received",
        "document_date": "scans_received",
        "delivery_date": "unloading",
    }
    for legacy_basis, trigger in trigger_by_legacy_basis.items():
        Organization.objects.filter(payment_term_basis=legacy_basis).update(
            payment_trigger=trigger
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0083_organization_authority_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_day_type',
            field=models.CharField(choices=[('calendar', 'Календарные дни'), ('banking', 'Банковские дни (рабочие)')], default='calendar', max_length=20, verbose_name='Вид отсрочки'),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_trigger',
            field=models.CharField(choices=[('originals_received', 'Получение оригиналов документов'), ('scans_received', 'Получение сканов документов'), ('unloading', 'По факту выгрузки'), ('edo_signed', 'После подписания документов по ЭДО')], default='unloading', max_length=30, verbose_name='Отсчёт срока оплаты'),
        ),
        migrations.RunPython(
            preserve_existing_payment_triggers,
            migrations.RunPython.noop,
        ),
    ]
