# Generated by Django 5.2.17 on 2026-09-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0088_userprofile_email_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrole',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('forwarder', 'Экспедитор-партнёр'), ('carrier', 'Перевозчик'), ('shipper', 'Грузоотправитель'), ('consignee', 'Грузополучатель')], max_length=20, verbose_name='Роль'),
        ),
    ]
