# Generated by Django 5.2.17 on 2026-09-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0089_executor_partner_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationlink',
            name='contractor_role',
            field=models.CharField(choices=[('forwarder', 'Экспедитор-партнёр'), ('carrier', 'Перевозчик')], max_length=20, verbose_name='Роль исполнителя'),
        ),
    ]
