# Generated by Django 5.2.17 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0090_transportation_executor_partner_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Клиент"),
                    ("forwarder", "Экспедитор-партнёр"),
                    ("carrier", "Перевозчик"),
                    ("shipper", "Грузоотправитель"),
                    ("consignee", "Грузополучатель"),
                    ("insurer", "Страховая компания"),
                ],
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
