# Generated by Django 5.2.17 on 2026-09-29 20:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0091_organizationrole_insurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='counterparty_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Контрагент из выписки'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='counterparty_tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН контрагента из выписки'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='operation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Сумма банковской операции'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='payment_purpose',
            field=models.TextField(blank=True, verbose_name='Назначение платежа'),
        ),
    ]
