# Generated by Django 5.2.17 on 2026-09-29 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0092_bank_statement_import_operation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('source_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Начало периода')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Конец периода')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_imports', to='crm.organizationbankaccount', verbose_name='Банковский счёт')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_bank_statements', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_imports', to='crm.organization', verbose_name='Наша компания')),
            ],
            options={
                'verbose_name': 'банковская выписка',
                'verbose_name_plural': 'банковские выписки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='crm.bankstatementimport', verbose_name='Банковская выписка'),
        ),
    ]
