# Generated by Django 5.2.17 on 2026-09-29 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0093_bankstatementimport_bankstatement_import_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='source_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Контрольная сумма файла'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementimport',
            constraint=models.UniqueConstraint(fields=('bank_account', 'source_fingerprint'), name='unique_bank_statement_import_file_per_account'),
        ),
    ]
