# Generated by Django 5.2.17 on 2026-09-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0094_bankstatementimport_source_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Остаток на конец'),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Остаток на начало'),
        ),
    ]
