# Generated by Django 5.2.17 on 2026-09-29 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0095_bankstatementimport_closing_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер счёта страховой')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата счёта')),
                ('insurer_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма страховой')),
                ('customer_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='К перевыставлению клиенту')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('draft', 'Ожидает счёт'), ('invoiced', 'Счёт страховой получен'), ('paid', 'Оплачено')], default='draft', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('bank_statement_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_insurance', to='crm.bankstatementline')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_insurances', to='crm.organization')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_insurances', to='crm.transportation')),
            ],
            options={
                'verbose_name': 'страхование груза',
                'verbose_name_plural': 'страхование грузов',
                'ordering': ('-invoice_date', '-created_at'),
            },
        ),
    ]
