# Generated by Django 5.2.17 on 2026-09-29 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0096_cargoinsurance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shipmentdocumentline',
            name='unique_accounting_document_transportation',
        ),
        migrations.AddField(
            model_name='shipmentdocumentline',
            name='cargo_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='crm.cargoinsurance'),
        ),
    ]
