# Generated by Django 5.2.17 on 2026-09-29 21:18

from django.db import migrations, models


def include_existing_insurance(apps, schema_editor):
    CargoInsurance = apps.get_model("crm", "CargoInsurance")
    Transportation = apps.get_model("crm", "Transportation")
    for insurance in CargoInsurance.objects.filter(included_in_customer_rate=False):
        Transportation.objects.filter(pk=insurance.transportation_id).update(
            customer_amount=models.F("customer_amount") + insurance.customer_amount
        )
        insurance.included_in_customer_rate = True
        insurance.save(update_fields=["included_in_customer_rate"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0097_remove_shipmentdocumentline_unique_accounting_document_transportation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoinsurance',
            name='included_in_customer_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(include_existing_insurance, migrations.RunPython.noop),
    ]
