# Generated by Django 5.2.17 on 2026-09-30

from django.db import migrations, models


def include_existing_insurance_in_settlement(apps, schema_editor):
    CargoInsurance = apps.get_model("crm", "CargoInsurance")
    Transportation = apps.get_model("crm", "Transportation")
    SettlementMovement = apps.get_model("crm", "SettlementMovement")
    TripCharge = apps.get_model("crm", "TripCharge")

    for insurance in CargoInsurance.objects.filter(
        included_in_customer_settlement=False
    ):
        transportation = Transportation.objects.get(pk=insurance.transportation_id)
        if transportation.posting_status == "posted":
            SettlementMovement.objects.filter(
                transportation_id=transportation.pk,
                side="receivable",
                kind="accrual",
            ).update(amount=models.F("amount") + insurance.customer_amount)
            TripCharge.objects.filter(
                transportation_id=transportation.pk,
                direction="revenue",
            ).update(
                amount=models.F("amount") + insurance.customer_amount,
                amount_without_vat=models.F("amount_without_vat") + insurance.customer_amount,
            )
        insurance.included_in_customer_settlement = True
        insurance.save(update_fields=["included_in_customer_settlement"])


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0098_cargoinsurance_included_in_customer_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargoinsurance",
            name="included_in_customer_settlement",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            include_existing_insurance_in_settlement,
            migrations.RunPython.noop,
        ),
    ]
