# Generated by Django 5.2.17 on 2026-10-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("crm", "0099_cargoinsurance_included_in_customer_settlement")]

    operations = [
        migrations.CreateModel(
            name="PlannedPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("due_date", models.DateField(verbose_name="Дата платежа")),
                ("kind", models.CharField(choices=[("rent", "Аренда"), ("payroll", "Зарплата"), ("tax", "Налоги"), ("bank_fee", "Комиссия банка"), ("other", "Прочее")], default="other", max_length=20, verbose_name="Категория")),
                ("status", models.CharField(choices=[("planned", "Запланирован"), ("paid", "Оплачен"), ("cancelled", "Отменён")], default="planned", max_length=20, verbose_name="Статус")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Сумма")),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                ("description", models.CharField(max_length=255, verbose_name="Назначение")),
                ("notes", models.TextField(blank=True, verbose_name="Комментарий")),
                ("bank_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="planned_payments", to="crm.organizationbankaccount")),
                ("counterparty", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="planned_payment_counterparty", to="crm.organization")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_planned_payments", to=settings.AUTH_USER_MODEL)),
                ("owner_company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="planned_payments", to="crm.organization")),
            ],
            options={"verbose_name": "плановый платёж", "verbose_name_plural": "плановые платежи", "ordering": ("due_date", "pk")},
        )
    ]
