# Generated by Django 5.2.17 on 2026-10-01 10:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0100_plannedpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='boom_capacity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Грузоподъёмность стрелы, кг'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_day_type',
            field=models.CharField(choices=[('calendar', 'Календарные дни'), ('working', 'Рабочие дни'), ('banking', 'Банковские дни (рабочие)')], default='calendar', max_length=20, verbose_name='Вид отсрочки'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_trigger',
            field=models.CharField(choices=[('unloading', 'По факту выгрузки'), ('edo_signed', 'После подписания документов по ЭДО'), ('delivery_date', 'Дата доставки'), ('originals_received', 'Получение оригиналов документов'), ('scans_received', 'Получение сканов документов'), ('invoice_date', 'Выставление счёта'), ('act_signed', 'Подписание акта'), ('other', 'Другое событие')], default='delivery_date', max_length=30, verbose_name='Отсчёт срока оплаты от'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='payment_term_basis',
            field=models.CharField(choices=[('unloading', 'По факту выгрузки'), ('scans_received', 'Получение сканов документов'), ('edo_signed', 'После подписания документов по ЭДО'), ('delivery_date', 'Дата доставки'), ('document_date', 'Дата документа'), ('originals_received', 'Получение оригиналов')], default='delivery_date', max_length=30, verbose_name='Основание срока оплаты'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='customer_payment_day_type_snapshot',
            field=models.CharField(blank=True, choices=[('calendar', 'Календарные дни'), ('working', 'Рабочие дни'), ('banking', 'Банковские дни (рабочие)')], max_length=20, verbose_name='Вид отсрочки клиента на момент оформления'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='customer_payment_trigger_snapshot',
            field=models.CharField(blank=True, choices=[('unloading', 'По факту выгрузки'), ('edo_signed', 'После подписания документов по ЭДО'), ('delivery_date', 'Дата доставки'), ('originals_received', 'Получение оригиналов документов'), ('scans_received', 'Получение сканов документов'), ('invoice_date', 'Выставление счёта'), ('act_signed', 'Подписание акта'), ('other', 'Другое событие')], max_length=30, verbose_name='Событие оплаты клиента на момент оформления'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='executor_payment_day_type_snapshot',
            field=models.CharField(blank=True, choices=[('calendar', 'Календарные дни'), ('working', 'Рабочие дни'), ('banking', 'Банковские дни (рабочие)')], max_length=20, verbose_name='Вид отсрочки исполнителя на момент оформления'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='executor_payment_due_basis',
            field=models.CharField(choices=[('unloading', 'По факту выгрузки'), ('scans_received', 'Получение сканов документов'), ('edo_signed', 'После подписания документов по ЭДО'), ('delivery_date', 'Дата доставки'), ('document_date', 'Дата документа'), ('originals_received', 'Получение оригиналов документов')], default='delivery_date', max_length=30, verbose_name='Основание срока оплаты исполнителю'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='executor_payment_trigger_snapshot',
            field=models.CharField(blank=True, choices=[('unloading', 'По факту выгрузки'), ('edo_signed', 'После подписания документов по ЭДО'), ('delivery_date', 'Дата доставки'), ('originals_received', 'Получение оригиналов документов'), ('scans_received', 'Получение сканов документов'), ('invoice_date', 'Выставление счёта'), ('act_signed', 'Подписание акта'), ('other', 'Другое событие')], max_length=30, verbose_name='Событие оплаты исполнителя на момент оформления'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='payment_due_basis',
            field=models.CharField(choices=[('unloading', 'По факту выгрузки'), ('scans_received', 'Получение сканов документов'), ('edo_signed', 'После подписания документов по ЭДО'), ('delivery_date', 'Дата доставки'), ('document_date', 'Дата документа'), ('originals_received', 'Получение оригиналов документов')], default='delivery_date', max_length=30, verbose_name='Основание срока оплаты'),
        ),
        migrations.AlterField(
            model_name='transportorder',
            name='payment_due_basis',
            field=models.CharField(choices=[('unloading', 'По факту выгрузки'), ('scans_received', 'Получение сканов документов'), ('edo_signed', 'После подписания документов по ЭДО'), ('delivery_date', 'Дата доставки'), ('document_date', 'Дата документа'), ('originals_received', 'Получение оригиналов документов')], default='delivery_date', max_length=30, verbose_name='Основание срока оплаты'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kind',
            field=models.CharField(choices=[('truck', 'Грузовой автомобиль'), ('manipulator', 'Манипулятор'), ('tractor', 'Седельный тягач'), ('van', 'Фургон'), ('gazelle', 'Газель'), ('trailer', 'Прицеп'), ('semitrailer', 'Полуприцеп'), ('other', 'Другое')], max_length=20, verbose_name='Тип единицы'),
        ),
    ]
